// categories.js – Arcángel App (33 categorías completas, Advocaciones en posición 9)

const categories = [
  {
    nombre: "Miedo / Ansiedad",
    keywords: ["miedo","ansiedad","temor","angustia","preocupación","nervios","inquietud","susto","pánico","sobresalto"],
    referencias: [
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 56, versiculo: 4 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "Salmos", capitulo: 27, versiculo: 1 },
      { libro: "Josué", capitulo: 1, versiculo: 9 },
      { libro: "Mateo", capitulo: 6, versiculo: 34 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 34, versiculo: 5 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 118, versiculo: 6 },
      { libro: "Proverbios", capitulo: 29, versiculo: 25 },
      { libro: "Salmos", capitulo: 46, versiculo: 2 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 91, versiculo: 5 },
      { libro: "Lucas", capitulo: 12, versiculo: 25 },
      { libro: "Salmos", capitulo: 55, versiculo: 23 },
      { libro: "Salmos", capitulo: 112, versiculo: 7 },
      { libro: "Apocalipsis", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 56, versiculo: 12 },
      { libro: "Salmos", capitulo: 121, versiculo: 7 },
      { libro: "Isaías", capitulo: 35, versiculo: 4 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 15 },
      { libro: "Salmos", capitulo: 56, versiculo: 3 },
      { libro: "Proverbios", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 91, versiculo: 5 },
      { libro: "Isaías", capitulo: 54, versiculo: 4 },
      { libro: "Salmos", capitulo: 34, versiculo: 4 },
      { libro: "Lucas", capitulo: 12, versiculo: 7 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "Romanos", capitulo: 8, versiculo: 31 }
    ],
    fraseEmpatica: [
      "No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.",
      "El Señor está cerca de los quebrantados de corazón.",
      "Deposita tus preocupaciones en Él, que cuida de ti.",
      "La paz de Dios, que sobrepasa todo entendimiento, guardará tu corazón.",
      "Confía en el Señor con todo tu corazón y Él enderezará tus veredas.",
      "Aunque camine por valles oscuros, no temeré, porque Tú estás conmigo.",
      "El amor perfecto echa fuera el miedo.",
      "No dejes que tu corazón se turbe; confía en Dios.",
      "Dios es nuestro refugio y fortaleza, una ayuda siempre pronta en los peligros.",
      "El ángel del Señor acampa alrededor de los que le temen y los defiende."
    ]
  },
  {
    nombre: "Tristeza / Pena",
    keywords: ["tristeza","pena","deprimido","abatido","desánimo","llanto","lágrimas","dolor emocional","melancolía","desconsuelo"],
    referencias: [
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Mateo", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 30, versiculo: 5 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Isaías", capitulo: 61, versiculo: 3 },
      { libro: "Salmos", capitulo: 126, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 22 },
      { libro: "Salmos", capitulo: 56, versiculo: 8 },
      { libro: "Juan", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 31, versiculo: 9 },
      { libro: "Romanos", capitulo: 12, versiculo: 15 },
      { libro: "Salmos", capitulo: 116, versiculo: 8 },
      { libro: "Isaías", capitulo: 53, versiculo: 4 },
      { libro: "Salmos", capitulo: 38, versiculo: 9 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 28 },
      { libro: "Jeremías", capitulo: 31, versiculo: 13 },
      { libro: "Salmos", capitulo: 34, versiculo: 6 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Juan", capitulo: 14, versiculo: 1 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Filipenses", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 43, versiculo: 5 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 10 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Hebreos", capitulo: 4, versiculo: 16 }
    ],
    fraseEmpatica: [
      "El Señor está cerca de los quebrantados de corazón.",
      "Tus lágrimas son recogidas por Aquel que te ama.",
      "El consuelo de Dios sobrepasa toda tristeza.",
      "No estás solo en tu dolor; Él camina a tu lado.",
      "La alegría vendrá por la mañana.",
      "Dios enjugará cada lágrima de tus ojos.",
      "Bienaventurados los que lloran, porque recibirán consolación.",
      "En la oscuridad más profunda, su luz no se apaga.",
      "Entrega a Dios tus cargas, y Él te sostendrá.",
      "Aunque el llanto dure una noche, la alegría vendrá al amanecer."
    ]
  },
  {
    nombre: "Estrés / Agobio",
    keywords: ["estrés","agobio","cansancio","sobrecarga","presión","agotamiento","quemado","burnout","tension"],
    referencias: [
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Proverbios", capitulo: 3, versiculo: 5 },
      { libro: "Salmos", capitulo: 46, versiculo: 10 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 131, versiculo: 2 },
      { libro: "Lucas", capitulo: 10, versiculo: 41 },
      { libro: "Éxodo", capitulo: 33, versiculo: 14 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Isaías", capitulo: 26, versiculo: 3 },
      { libro: "Salmos", capitulo: 119, versiculo: 143 },
      { libro: "Romanos", capitulo: 8, versiculo: 6 },
      { libro: "Salmos", capitulo: 34, versiculo: 17 },
      { libro: "Mateo", capitulo: 6, versiculo: 34 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 },
      { libro: "Isaías", capitulo: 41, versiculo: 13 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Juan", capitulo: 16, versiculo: 33 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 8 },
      { libro: "Salmos", capitulo: 61, versiculo: 2 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 42, versiculo: 5 },
      { libro: "Marcos", capitulo: 6, versiculo: 31 },
      { libro: "Salmos", capitulo: 116, versiculo: 7 },
      { libro: "Lucas", capitulo: 12, versiculo: 25 }
    ],
    fraseEmpatica: [
      "Venid a mí todos los que estáis cansados y agobiados, y yo os haré descansar.",
      "No estás solo en esta carga; el Señor te sostiene.",
      "Deja tu ansiedad en sus manos, porque Él cuida de ti.",
      "La paz os dejo, mi paz os doy; no se turbe vuestro corazón.",
      "Los que confían en el Señor renovarán sus fuerzas.",
      "Descansa en la certeza de que Dios nunca te dará más de lo que puedas soportar.",
      "A veces la oración más poderosa es simplemente respirar y decir: 'Señor, aquí estoy'.",
      "Dios no te pide que seas perfecto, solo que confíes.",
      "En el silencio encontrarás la fuerza que necesitas.",
      "Tus hombros no están hechos para cargar el mundo; suelta y confía."
    ]
  },
  {
    nombre: "Soledad",
    keywords: ["soledad","solo","abandonado","aislado","me siento solo","sin nadie","solitaria"],
    referencias: [
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Mateo", capitulo: 28, versiculo: 20 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Hebreos", capitulo: 13, versiculo: 5 },
      { libro: "Salmos", capitulo: 27, versiculo: 10 },
      { libro: "Juan", capitulo: 14, versiculo: 18 },
      { libro: "Salmos", capitulo: 102, versiculo: 7 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 142, versiculo: 4 },
      { libro: "Isaías", capitulo: 49, versiculo: 15 },
      { libro: "Salmos", capitulo: 25, versiculo: 16 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 14 },
      { libro: "Salmos", capitulo: 38, versiculo: 11 },
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "Josué", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Lucas", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Apocalipsis", capitulo: 3, versiculo: 20 },
      { libro: "Salmos", capitulo: 33, versiculo: 20 },
      { libro: "Juan", capitulo: 16, versiculo: 32 },
      { libro: "Salmos", capitulo: 39, versiculo: 12 },
      { libro: "Proverbios", capitulo: 18, versiculo: 24 },
      { libro: "Salmos", capitulo: 145, versiculo: 18 },
      { libro: "2 Timoteo", capitulo: 4, versiculo: 17 },
      { libro: "Salmos", capitulo: 73, versiculo: 23 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 91, versiculo: 15 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 }
    ],
    fraseEmpatica: [
      "Dios habita en una casa donde nadie está solo.",
      "Yo estoy contigo todos los días, hasta el fin del mundo.",
      "Aunque mi padre y mi madre me abandonen, el Señor me recogerá.",
      "No te dejaré ni te abandonaré.",
      "El Señor está cerca de quienes lo invocan.",
      "En la soledad más profunda, Dios susurra: 'Aquí estoy'.",
      "Nunca caminas solo; cada paso lo das con un ángel a tu lado.",
      "La soledad es la antesala donde Dios te encuentra a solas.",
      "Aunque no veas a nadie, el cielo entero te acompaña.",
      "Él pone a los solitarios en familia."
    ]
  },
  {
    nombre: "Desesperanza / Desánimo",
    keywords: ["desesperanza","desánimo","sin esperanza","rendirse","no puedo más","darse por vencido","desalentado"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 42, versiculo: 5 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 16 },
      { libro: "Salmos", capitulo: 33, versiculo: 22 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 21 },
      { libro: "Salmos", capitulo: 130, versiculo: 5 },
      { libro: "Miqueas", capitulo: 7, versiculo: 7 },
      { libro: "Romanos", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 146, versiculo: 5 },
      { libro: "Jeremías", capitulo: 31, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Habacuc", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 71, versiculo: 14 },
      { libro: "Gálatas", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 119, versiculo: 81 },
      { libro: "Proverbios", capitulo: 24, versiculo: 16 },
      { libro: "Salmos", capitulo: 43, versiculo: 5 },
      { libro: "Isaías", capitulo: 61, versiculo: 3 },
      { libro: "Salmos", capitulo: 9, versiculo: 18 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 33, versiculo: 18 },
      { libro: "2 Tesalonicenses", capitulo: 2, versiculo: 16 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Filipenses", capitulo: 1, versiculo: 6 }
    ],
    fraseEmpatica: [
      "Porque yo sé los planes que tengo para ti, planes de bien y no de mal.",
      "El Dios de la esperanza os llene de todo gozo y paz en la fe.",
      "¿Por qué te abates, alma mía? Espera en Dios.",
      "Los que esperan en el Señor renovarán sus fuerzas.",
      "Aunque el justo caiga siete veces, se levantará.",
      "No te rindas; la cosecha llegará a su tiempo.",
      "Dios no ha terminado contigo. Esta pausa es parte del plan.",
      "La esperanza es el ancla del alma.",
      "Cuando sientas que no puedes más, Él cargará contigo.",
      "Después de la tormenta más oscura, sale el sol más brillante."
    ]
  },
  {
    nombre: "Cansancio / Fatiga",
    keywords: ["cansancio","fatiga","agotado","sin fuerzas","extenuado","rendido"],
    referencias: [
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Isaías", capitulo: 40, versiculo: 29 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Jeremías", capitulo: 31, versiculo: 25 },
      { libro: "Salmos", capitulo: 62, versiculo: 1 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 116, versiculo: 7 },
      { libro: "Éxodo", capitulo: 33, versiculo: 14 },
      { libro: "Salmos", capitulo: 127, versiculo: 2 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 7 },
      { libro: "Salmos", capitulo: 38, versiculo: 9 },
      { libro: "Mateo", capitulo: 6, versiculo: 33 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "2 Corintios", capitulo: 12, versiculo: 9 },
      { libro: "Salmos", capitulo: 68, versiculo: 35 },
      { libro: "Deuteronomio", capitulo: 33, versiculo: 25 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 121, versiculo: 3 },
      { libro: "Proverbios", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 4, versiculo: 8 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Colosenses", capitulo: 1, versiculo: 11 },
      { libro: "Salmos", capitulo: 132, versiculo: 14 },
      { libro: "Marcos", capitulo: 6, versiculo: 31 },
      { libro: "Salmos", capitulo: 90, versiculo: 14 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 25, versiculo: 17 },
      { libro: "Romanos", capitulo: 15, versiculo: 32 },
      { libro: "Salmos", capitulo: 34, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Venid a mí los que estáis cansados y agobiados, y yo os haré descansar.",
      "Él da fuerzas al cansado y multiplica el vigor del que no tiene.",
      "En lugares de verdes pastos me hace descansar.",
      "Dios te ofrece un oasis en medio del desierto.",
      "Descansa en el Señor; Él se encarga de lo que a ti te supera.",
      "Cuando ya no puedas más, recuerda: su fuerza se perfecciona en tu debilidad.",
      "Respira hondo y deja que la paz de Dios llene tu ser.",
      "No estás diseñado para correr sin parar. Descansa en Él.",
      "El sueño del justo es tranquilo, porque Dios vela su descanso.",
      "Recuesta tu cabeza en el regazo del Padre."
    ]
  },
  {
    nombre: "Enfermedad / Dolor",
    keywords: ["enfermedad","dolor","enfermo","malestar","padecimiento","sufrimiento físico","hospital","cama"],
    referencias: [
      { libro: "Jeremías", capitulo: 17, versiculo: 14 },
      { libro: "Salmos", capitulo: 41, versiculo: 3 },
      { libro: "Éxodo", capitulo: 15, versiculo: 26 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Isaías", capitulo: 53, versiculo: 5 },
      { libro: "Salmos", capitulo: 30, versiculo: 2 },
      { libro: "Mateo", capitulo: 4, versiculo: 24 },
      { libro: "Salmos", capitulo: 6, versiculo: 2 },
      { libro: "Santiago", capitulo: 5, versiculo: 15 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Jeremías", capitulo: 30, versiculo: 17 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Marcos", capitulo: 5, versiculo: 34 },
      { libro: "Salmos", capitulo: 38, versiculo: 21 },
      { libro: "3 Juan", capitulo: 1, versiculo: 2 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Isaías", capitulo: 57, versiculo: 18 },
      { libro: "Salmos", capitulo: 116, versiculo: 8 },
      { libro: "Mateo", capitulo: 8, versiculo: 17 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 34, versiculo: 19 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 15 },
      { libro: "Salmos", capitulo: 91, versiculo: 15 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 56, versiculo: 13 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 71 },
      { libro: "Lucas", capitulo: 8, versiculo: 50 },
      { libro: "Salmos", capitulo: 25, versiculo: 18 },
      { libro: "Romanos", capitulo: 8, versiculo: 18 },
      { libro: "Salmos", capitulo: 9, versiculo: 13 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 24 }
    ],
    fraseEmpatica: [
      "Sáname, Señor, y seré sanado; sálvame, y seré salvo.",
      "Él envió su palabra y los sanó.",
      "Por sus llagas hemos sido sanados.",
      "El Señor te sostendrá en el lecho del dolor.",
      "Tu fe te ha sanado; ve en paz.",
      "Dios no te abandona en la enfermedad; está más cerca que nunca.",
      "Cada dolor ofrecido a Dios se convierte en semilla de gloria.",
      "Aunque el cuerpo se debilite, el alma se renueva en Él.",
      "El médico divino conoce tu dolor y te abraza.",
      "No hay enfermedad que Dios no pueda sanar, ni sufrimiento que Él no consuele."
    ]
  },
  {
    nombre: "Duelo / Pérdida",
    keywords: ["duelo","pérdida","muerte","fallecimiento","difunto","luto","adiós","perder a alguien"],
    referencias: [
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Mateo", capitulo: 5, versiculo: 4 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "1 Tesalonicenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Juan", capitulo: 11, versiculo: 25 },
      { libro: "Salmos", capitulo: 116, versiculo: 15 },
      { libro: "Romanos", capitulo: 14, versiculo: 8 },
      { libro: "Salmos", capitulo: 61, versiculo: 2 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 30, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 32 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 55 },
      { libro: "Salmos", capitulo: 48, versiculo: 14 },
      { libro: "Eclesiastés", capitulo: 3, versiculo: 1 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Apocalipsis", capitulo: 14, versiculo: 13 },
      { libro: "Salmos", capitulo: 126, versiculo: 6 },
      { libro: "Hebreos", capitulo: 13, versiculo: 5 },
      { libro: "Salmos", capitulo: 119, versiculo: 50 },
      { libro: "Isaías", capitulo: 66, versiculo: 13 },
      { libro: "Salmos", capitulo: 56, versiculo: 8 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Lucas", capitulo: 7, versiculo: 13 },
      { libro: "Salmos", capitulo: 18, versiculo: 28 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 },
      { libro: "Juan", capitulo: 14, versiculo: 2 },
      { libro: "Salmos", capitulo: 91, versiculo: 11 }
    ],
    fraseEmpatica: [
      "Bienaventurados los que lloran, porque ellos recibirán consolación.",
      "El Señor está cerca de los quebrantados de corazón.",
      "Él enjugará toda lágrima de sus ojos.",
      "No quiero que ignoréis acerca de los que duermen, para que no os entristezcáis como los que no tienen esperanza.",
      "Aunque camine por el valle de sombra de muerte, no temeré.",
      "Tu ser querido no se ha ido, solo se ha adelantado.",
      "El duelo es la forma más pura de amor. Dios lo entiende.",
      "Él recoge tus lágrimas en un frasco; cada una cuenta.",
      "La muerte no es el final, es el comienzo de la vida eterna.",
      "Jesús lloró junto a la tumba de su amigo. Él llora contigo."
    ]
  },
  {
    nombre: "Advocaciones marianas / Virgen María",
    keywords: ["maría","virgen","madre","advocación","guadalupe","rosario"],
    referencias: [
      { libro: "Lucas", capitulo: 1, versiculo: 46 },
      { libro: "Juan", capitulo: 19, versiculo: 26 },
      { libro: "Lucas", capitulo: 1, versiculo: 38 },
      { libro: "Hechos", capitulo: 1, versiculo: 14 },
      { libro: "Lucas", capitulo: 2, versiculo: 19 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 1 },
      { libro: "Lucas", capitulo: 1, versiculo: 42 },
      { libro: "Juan", capitulo: 2, versiculo: 5 },
      { libro: "Lucas", capitulo: 1, versiculo: 48 },
      { libro: "Cantar", capitulo: 2, versiculo: 14 },
      { libro: "Lucas", capitulo: 11, versiculo: 27 },
      { libro: "Mateo", capitulo: 12, versiculo: 50 },
      { libro: "Lucas", capitulo: 2, versiculo: 34 },
      { libro: "Juan", capitulo: 19, versiculo: 27 },
      { libro: "Lucas", capitulo: 1, versiculo: 35 },
      { libro: "Génesis", capitulo: 3, versiculo: 15 },
      { libro: "Lucas", capitulo: 1, versiculo: 28 },
      { libro: "Salmos", capitulo: 45, versiculo: 9 },
      { libro: "Lucas", capitulo: 1, versiculo: 45 },
      { libro: "Proverbios", capitulo: 31, versiculo: 10 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 5 },
      { libro: "Eclesiástico", capitulo: 24, versiculo: 1 },
      { libro: "Lucas", capitulo: 2, versiculo: 7 },
      { libro: "Mateo", capitulo: 1, versiculo: 23 },
      { libro: "Lucas", capitulo: 2, versiculo: 51 },
      { libro: "Marcos", capitulo: 3, versiculo: 35 },
      { libro: "Lucas", capitulo: 8, versiculo: 21 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 17 },
      { libro: "Lucas", capitulo: 1, versiculo: 43 },
      { libro: "Gálatas", capitulo: 4, versiculo: 4 },
      { libro: "Lucas", capitulo: 1, versiculo: 50 },
      { libro: "Sofonías", capitulo: 3, versiculo: 14 },
      { libro: "Lucas", capitulo: 1, versiculo: 47 }
    ],
    fraseEmpatica: [
      "Engrandece mi alma al Señor, y mi espíritu se regocija en Dios mi Salvador.",
      "Mujer, he ahí tu hijo.",
      "He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.",
      "María guardaba todas estas cosas, meditándolas en su corazón.",
      "Una gran señal apareció en el cielo: una mujer vestida del sol.",
      "Acude a María, ella te guiará a Jesús.",
      "La Madre celestial te cubre con su manto de amor.",
      "En cada advocación mariana, Dios nos recuerda que somos hijos amados.",
      "Reza el rosario, cadena dulce que une la tierra con el cielo.",
      "Santa María, Madre de Dios, ruega por nosotros pecadores."
    ]
  },
  {
    nombre: "Paz interior",
    keywords: ["paz interior","calma","serenidad","tranquilidad","paz mental","sosiego"],
    referencias: [
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Filipenses", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Isaías", capitulo: 26, versiculo: 3 },
      { libro: "Salmos", capitulo: 4, versiculo: 8 },
      { libro: "Números", capitulo: 6, versiculo: 26 },
      { libro: "Salmos", capitulo: 119, versiculo: 165 },
      { libro: "Isaías", capitulo: 32, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 11 },
      { libro: "Mateo", capitulo: 5, versiculo: 9 },
      { libro: "Salmos", capitulo: 34, versiculo: 14 },
      { libro: "Romanos", capitulo: 14, versiculo: 17 },
      { libro: "Salmos", capitulo: 72, versiculo: 7 },
      { libro: "Colosenses", capitulo: 3, versiculo: 15 },
      { libro: "Salmos", capitulo: 122, versiculo: 6 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 16 },
      { libro: "Salmos", capitulo: 85, versiculo: 8 },
      { libro: "Gálatas", capitulo: 5, versiculo: 22 },
      { libro: "Salmos", capitulo: 46, versiculo: 10 },
      { libro: "Juan", capitulo: 16, versiculo: 33 },
      { libro: "Salmos", capitulo: 131, versiculo: 2 },
      { libro: "Proverbios", capitulo: 12, versiculo: 20 },
      { libro: "Salmos", capitulo: 37, versiculo: 37 },
      { libro: "Efesios", capitulo: 2, versiculo: 14 },
      { libro: "Salmos", capitulo: 55, versiculo: 18 },
      { libro: "Isaías", capitulo: 55, versiculo: 12 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Mateo", capitulo: 11, versiculo: 29 },
      { libro: "Salmos", capitulo: 62, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 119, versiculo: 76 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 147, versiculo: 14 }
    ],
    fraseEmpatica: [
      "La paz os dejo, mi paz os doy; no se turbe vuestro corazón.",
      "La paz de Dios, que sobrepasa todo entendimiento, guardará vuestros corazones.",
      "El Señor bendice a su pueblo con paz.",
      "Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera.",
      "En paz me acostaré y asimismo dormiré.",
      "Quédate quieto, reconoce que Él es Dios.",
      "La paz no es ausencia de tormenta, es calma en medio de ella.",
      "Respira. Dios está en el centro de tu ser.",
      "El fruto del Espíritu es paz.",
      "Cierra los ojos. El cielo te envuelve en su manto de tranquilidad."
    ]
  },
  {
    nombre: "Fortaleza / Valentía",
    keywords: ["fortaleza","valentía","fuerza","coraje","ánimo","valiente","no puedo más"],
    referencias: [
      { libro: "Josué", capitulo: 1, versiculo: 9 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "2 Timoteo", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 18, versiculo: 32 },
      { libro: "Efesios", capitulo: 6, versiculo: 10 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 138, versiculo: 3 },
      { libro: "1 Corintios", capitulo: 16, versiculo: 13 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Isaías", capitulo: 40, versiculo: 29 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Romanos", capitulo: 8, versiculo: 31 },
      { libro: "Salmos", capitulo: 84, versiculo: 5 },
      { libro: "Habacuc", capitulo: 3, versiculo: 19 },
      { libro: "Salmos", capitulo: 68, versiculo: 35 },
      { libro: "Isaías", capitulo: 12, versiculo: 2 },
      { libro: "Salmos", capitulo: 121, versiculo: 2 },
      { libro: "1 Juan", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 144, versiculo: 1 },
      { libro: "Proverbios", capitulo: 24, versiculo: 10 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Éxodo", capitulo: 15, versiculo: 2 },
      { libro: "Salmos", capitulo: 56, versiculo: 4 },
      { libro: "Lucas", capitulo: 1, versiculo: 37 },
      { libro: "Salmos", capitulo: 44, versiculo: 5 },
      { libro: "Nehemías", capitulo: 8, versiculo: 10 },
      { libro: "Salmos", capitulo: 18, versiculo: 39 },
      { libro: "Mateo", capitulo: 19, versiculo: 26 },
      { libro: "Salmos", capitulo: 60, versiculo: 12 }
    ],
    fraseEmpatica: [
      "Esfuérzate y sé valiente; no temas ni desmayes.",
      "El Señor es mi luz y mi salvación, ¿de quién temeré?",
      "Todo lo puedo en Cristo que me fortalece.",
      "Dios es nuestro refugio y fortaleza.",
      "No te ha dado Dios espíritu de cobardía, sino de poder, amor y dominio propio.",
      "Levántate. La fuerza que necesitas ya ha sido puesta en ti.",
      "Eres más fuerte de lo que crees, porque Dios pelea contigo.",
      "Cuando sientas que flaqueas, recuerda: sus alas te cubren.",
      "La valentía no es no tener miedo, es seguir adelante a pesar de él.",
      "El Dios que venció la muerte vive en ti."
    ]
  },
  {
    nombre: "Protección / Refugio",
    keywords: ["protección","refugio","seguro","escudo","amparo","defensa","peligro"],
    referencias: [
      { libro: "Salmos", capitulo: 91, versiculo: 2 },
      { libro: "Proverbios", capitulo: 18, versiculo: 10 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "Salmos", capitulo: 121, versiculo: 7 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 3 },
      { libro: "Salmos", capitulo: 32, versiculo: 7 },
      { libro: "Isaías", capitulo: 54, versiculo: 17 },
      { libro: "Salmos", capitulo: 27, versiculo: 5 },
      { libro: "Nahúm", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 34, versiculo: 7 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 125, versiculo: 2 },
      { libro: "Salmo", capitulo: 140, versiculo: 4 },
      { libro: "Juan", capitulo: 17, versiculo: 15 },
      { libro: "Salmos", capitulo: 61, versiculo: 4 },
      { libro: "1 Pedro", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Mateo", capitulo: 6, versiculo: 13 },
      { libro: "Salmos", capitulo: 41, versiculo: 2 },
      { libro: "Efesios", capitulo: 6, versiculo: 11 },
      { libro: "Salmos", capitulo: 91, versiculo: 11 },
      { libro: "2 Samuel", capitulo: 22, versiculo: 3 },
      { libro: "Salmos", capitulo: 16, versiculo: 1 },
      { libro: "Isaías", capitulo: 43, versiculo: 2 },
      { libro: "Salmos", capitulo: 18, versiculo: 2 },
      { libro: "Proverbios", capitulo: 30, versiculo: 5 },
      { libro: "Salmos", capitulo: 144, versiculo: 2 },
      { libro: "Lucas", capitulo: 10, versiculo: 19 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "Salmos", capitulo: 55, versiculo: 16 },
      { libro: "Jeremías", capitulo: 15, versiculo: 21 },
      { libro: "Salmos", capitulo: 145, versiculo: 20 }
    ],
    fraseEmpatica: [
      "El que habita al amparo del Altísimo descansará a la sombra del Omnipotente.",
      "Torre fuerte es el nombre del Señor; a ella corre el justo y está a salvo.",
      "Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.",
      "El Señor te guardará de todo mal; Él guardará tu alma.",
      "El Señor es fiel, y Él os fortalecerá y os protegerá del maligno.",
      "Bajo sus alas encuentras el refugio más seguro.",
      "No temas; mayor es el que está contigo que el que está en el mundo.",
      "Dios envía a sus ángeles para que te guarden en todos tus caminos.",
      "En la tormenta más feroz, Él es tu ancla.",
      "Muros invisibles te rodean; el cielo entero vela por ti."
    ]
  },
  {
    nombre: "Fe / Confianza en Dios",
    keywords: ["fe","confianza","creer","duda","confiar","credulidad"],
    referencias: [
      { libro: "Hebreos", capitulo: 11, versiculo: 1 },
      { libro: "Proverbios", capitulo: 3, versiculo: 5 },
      { libro: "Salmos", capitulo: 37, versiculo: 5 },
      { libro: "Marcos", capitulo: 11, versiculo: 22 },
      { libro: "Salmos", capitulo: 56, versiculo: 3 },
      { libro: "Mateo", capitulo: 17, versiculo: 20 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Isaías", capitulo: 26, versiculo: 4 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Romanos", capitulo: 10, versiculo: 17 },
      { libro: "Salmos", capitulo: 9, versiculo: 10 },
      { libro: "2 Corintios", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 40, versiculo: 4 },
      { libro: "Juan", capitulo: 20, versiculo: 29 },
      { libro: "Salmos", capitulo: 118, versiculo: 8 },
      { libro: "Santiago", capitulo: 1, versiculo: 6 },
      { libro: "Salmos", capitulo: 25, versiculo: 2 },
      { libro: "1 Juan", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 32, versiculo: 10 },
      { libro: "Mateo", capitulo: 21, versiculo: 22 },
      { libro: "Salmos", capitulo: 115, versiculo: 11 },
      { libro: "Gálatas", capitulo: 2, versiculo: 20 },
      { libro: "Salmos", capitulo: 31, versiculo: 14 },
      { libro: "Efesios", capitulo: 2, versiculo: 8 },
      { libro: "Salmos", capitulo: 121, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 19 },
      { libro: "Salmos", capitulo: 112, versiculo: 7 },
      { libro: "Lucas", capitulo: 1, versiculo: 37 },
      { libro: "Salmos", capitulo: 146, versiculo: 3 },
      { libro: "Romanos", capitulo: 8, versiculo: 28 },
      { libro: "Salmos", capitulo: 34, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 84, versiculo: 12 }
    ],
    fraseEmpatica: [
      "La fe es la certeza de lo que se espera, la convicción de lo que no se ve.",
      "Confía en el Señor con todo tu corazón, y no te apoyes en tu propia prudencia.",
      "Encomienda al Señor tu camino, confía en Él, y Él actuará.",
      "Tened fe en Dios.",
      "Bienaventurados los que no vieron y creyeron.",
      "Cuando la duda te invada, recuerda: un grano de fe mueve montañas.",
      "Dios no te ha fallado nunca y no empezará ahora.",
      "La confianza no es saber lo que viene, sino saber quién viene contigo.",
      "Cada paso que das en la oscuridad, Él ya lo iluminó.",
      "No necesitas entender el plan; solo confiar en el Arquitecto."
    ]
  },
  {
    nombre: "Oración / Vida espiritual",
    keywords: ["oración","rezar","vida espiritual","comunión","hablar con Dios","espiritualidad","meditación"],
    referencias: [
      { libro: "Mateo", capitulo: 6, versiculo: 6 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 17 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 145, versiculo: 18 },
      { libro: "Jeremías", capitulo: 33, versiculo: 3 },
      { libro: "Salmos", capitulo: 55, versiculo: 17 },
      { libro: "Lucas", capitulo: 18, versiculo: 1 },
      { libro: "Salmos", capitulo: 5, versiculo: 3 },
      { libro: "Romanos", capitulo: 12, versiculo: 12 },
      { libro: "Salmos", capitulo: 141, versiculo: 2 },
      { libro: "Marcos", capitulo: 1, versiculo: 35 },
      { libro: "Salmos", capitulo: 88, versiculo: 13 },
      { libro: "Santiago", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 102, versiculo: 1 },
      { libro: "Efesios", capitulo: 6, versiculo: 18 },
      { libro: "Salmos", capitulo: 17, versiculo: 1 },
      { libro: "Mateo", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 109, versiculo: 4 },
      { libro: "Hechos", capitulo: 1, versiculo: 14 },
      { libro: "Salmos", capitulo: 65, versiculo: 2 },
      { libro: "1 Juan", capitulo: 5, versiculo: 14 },
      { libro: "Salmos", capitulo: 28, versiculo: 6 },
      { libro: "Daniel", capitulo: 6, versiculo: 10 },
      { libro: "Salmos", capitulo: 119, versiculo: 147 },
      { libro: "Mateo", capitulo: 26, versiculo: 41 },
      { libro: "Salmos", capitulo: 54, versiculo: 2 },
      { libro: "Colosenses", capitulo: 4, versiculo: 2 },
      { libro: "Salmos", capitulo: 145, versiculo: 1 },
      { libro: "Lucas", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 19, versiculo: 14 },
      { libro: "Salmos", capitulo: 34, versiculo: 15 },
      { libro: "Isaías", capitulo: 65, versiculo: 24 },
      { libro: "Salmos", capitulo: 143, versiculo: 1 }
    ],
    fraseEmpatica: [
      "Tú, cuando ores, entra en tu aposento, cierra la puerta, y ora a tu Padre que está en secreto.",
      "Orad sin cesar.",
      "Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios.",
      "Cercano está el Señor a todos los que le invocan.",
      "Clama a mí y yo te responderé.",
      "La oración más poderosa es la que sale del corazón, aunque no encuentre palabras.",
      "Cuando no sepas qué decir, simplemente di: 'Aquí estoy, Señor'.",
      "Habla con Dios como con un amigo; Él te escucha.",
      "Cada suspiro puede ser una oración.",
      "Dios no exige palabras bonitas, solo un corazón sincero."
    ]
  },
  {
    nombre: "Salud física y espiritual",
    keywords: ["salud","bienestar","sano","cuidado","cuerpo","mente sana"],
    referencias: [
      { libro: "3 Juan", capitulo: 1, versiculo: 2 },
      { libro: "1 Corintios", capitulo: 6, versiculo: 19 },
      { libro: "Éxodo", capitulo: 15, versiculo: 26 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Proverbios", capitulo: 4, versiculo: 20 },
      { libro: "Isaías", capitulo: 58, versiculo: 8 },
      { libro: "Salmos", capitulo: 38, versiculo: 3 },
      { libro: "Jeremías", capitulo: 33, versiculo: 6 },
      { libro: "Salmos", capitulo: 41, versiculo: 3 },
      { libro: "1 Timoteo", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 30, versiculo: 2 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 15 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Marcos", capitulo: 5, versiculo: 34 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Lucas", capitulo: 9, versiculo: 11 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Romanos", capitulo: 12, versiculo: 1 },
      { libro: "Salmos", capitulo: 6, versiculo: 2 },
      { libro: "Proverbios", capitulo: 14, versiculo: 30 },
      { libro: "Salmos", capitulo: 119, versiculo: 73 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 139, versiculo: 14 },
      { libro: "Mateo", capitulo: 4, versiculo: 23 },
      { libro: "Salmos", capitulo: 34, versiculo: 19 },
      { libro: "Santiago", capitulo: 5, versiculo: 15 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Apocalipsis", capitulo: 22, versiculo: 2 },
      { libro: "Salmos", capitulo: 91, versiculo: 16 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 24 },
      { libro: "Salmos", capitulo: 37, versiculo: 3 }
    ],
    fraseEmpatica: [
      "Amado, ruego que seas prosperado en todas las cosas y que tengas salud, así como prospera tu alma.",
      "Vuestro cuerpo es templo del Espíritu Santo.",
      "Él sana a los quebrantados de corazón y venda sus heridas.",
      "Yo soy el Señor, tu sanador.",
      "La salud del cuerpo y del alma vienen de Dios.",
      "Cuida tu cuerpo, porque es el sagrario donde habita Dios.",
      "Una mente en paz es un cuerpo sano.",
      "Dios te quiere completo: alma, mente y cuerpo.",
      "Cada latido es un regalo divino.",
      "La verdadera salud es estar en armonía con tu Creador."
    ]
  },
  {
    nombre: "Sanación interior / Liberación",
    keywords: ["sanación interior","liberación","curación","heridas","pasado","trauma"],
    referencias: [
      { libro: "Isaías", capitulo: 61, versiculo: 1 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Joel", capitulo: 2, versiculo: 25 },
      { libro: "Lucas", capitulo: 4, versiculo: 18 },
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Jeremías", capitulo: 30, versiculo: 17 },
      { libro: "Salmos", capitulo: 103, versiculo: 4 },
      { libro: "2 Corintios", capitulo: 5, versiculo: 17 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "Ezequiel", capitulo: 36, versiculo: 26 },
      { libro: "Salmos", capitulo: 40, versiculo: 2 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Romanos", capitulo: 8, versiculo: 1 },
      { libro: "Salmos", capitulo: 32, versiculo: 5 },
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Isaías", capitulo: 43, versiculo: 18 },
      { libro: "Salmos", capitulo: 126, versiculo: 1 },
      { libro: "Juan", capitulo: 8, versiculo: 36 },
      { libro: "Salmos", capitulo: 25, versiculo: 7 },
      { libro: "Gálatas", capitulo: 5, versiculo: 1 },
      { libro: "Salmos", capitulo: 71, versiculo: 20 },
      { libro: "Filipenses", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 119, versiculo: 133 },
      { libro: "Colosenses", capitulo: 1, versiculo: 13 },
      { libro: "Salmos", capitulo: 18, versiculo: 19 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 5 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Hebreos", capitulo: 12, versiculo: 1 },
      { libro: "Salmos", capitulo: 55, versiculo: 18 },
      { libro: "Isaías", capitulo: 53, versiculo: 5 },
      { libro: "Salmos", capitulo: 30, versiculo: 11 }
    ],
    fraseEmpatica: [
      "El Espíritu del Señor está sobre mí… para sanar a los quebrantados de corazón.",
      "Él restaura lo que el tiempo se llevó.",
      "Os restauraré los años que comió la oruga.",
      "De modo que si alguno está en Cristo, nueva criatura es.",
      "Os daré un corazón nuevo y pondré un espíritu nuevo dentro de vosotros.",
      "Tus cicatrices no te definen; son trofeos de batallas superadas.",
      "Dios no solo olvida tus pecados, también sana sus consecuencias.",
      "El pasado ya no tiene poder sobre ti; Él te ha liberado.",
      "Deja que el amor divino llene cada grieta de tu historia.",
      "Eres libre, aunque aún no lo sientas. Camina en esa verdad."
    ]
  },
  {
    nombre: "Arrepentimiento / Confesión",
    keywords: ["arrepentimiento","confesión","culpa","perdón","pecado","remordimiento"],
    referencias: [
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 51, versiculo: 1 },
      { libro: "Proverbios", capitulo: 28, versiculo: 13 },
      { libro: "Salmos", capitulo: 32, versiculo: 5 },
      { libro: "Hechos", capitulo: 3, versiculo: 19 },
      { libro: "Salmos", capitulo: 38, versiculo: 18 },
      { libro: "Isaías", capitulo: 1, versiculo: 18 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Lucas", capitulo: 15, versiculo: 21 },
      { libro: "Salmos", capitulo: 25, versiculo: 11 },
      { libro: "Ezequiel", capitulo: 18, versiculo: 21 },
      { libro: "Salmos", capitulo: 130, versiculo: 4 },
      { libro: "Mateo", capitulo: 3, versiculo: 2 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Hechos", capitulo: 2, versiculo: 38 },
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Daniel", capitulo: 9, versiculo: 9 },
      { libro: "Salmos", capitulo: 86, versiculo: 5 },
      { libro: "Romanos", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 59 },
      { libro: "Lucas", capitulo: 18, versiculo: 13 },
      { libro: "Salmos", capitulo: 19, versiculo: 12 },
      { libro: "Marcos", capitulo: 1, versiculo: 15 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "2 Crónicas", capitulo: 7, versiculo: 14 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "1 Juan", capitulo: 2, versiculo: 1 },
      { libro: "Salmos", capitulo: 79, versiculo: 9 },
      { libro: "Proverbios", capitulo: 28, versiculo: 13 },
      { libro: "Salmos", capitulo: 41, versiculo: 4 },
      { libro: "Jonás", capitulo: 3, versiculo: 10 },
      { libro: "Salmos", capitulo: 69, versiculo: 5 },
      { libro: "Santiago", capitulo: 5, versiculo: 16 }
    ],
    fraseEmpatica: [
      "Si confesamos nuestros pecados, Él es fiel y justo para perdonar nuestros pecados.",
      "Ten piedad de mí, oh Dios, conforme a tu gran amor.",
      "El que encubre sus pecados no prosperará; mas el que los confiesa y se aparta alcanzará misericordia.",
      "Venid luego, dice el Señor, y estemos a cuenta: aunque vuestros pecados sean como la grana, como la nieve serán emblanquecidos.",
      "Los sacrificios de Dios son el espíritu quebrantado; al corazón contrito y humillado no desprecias tú, oh Dios.",
      "No temas acercarte a Dios con tu culpa; Él ya la conocía y aun así te ama.",
      "El arrepentimiento no es humillación, es la puerta hacia la libertad.",
      "Cada confesión sincera borra una mancha y enciende una luz.",
      "Dios no se cansa de perdonar; somos nosotros los que nos cansamos de pedir perdón.",
      "Vuelve a casa. El Padre te espera con los brazos abiertos."
    ]
  },
  {
    nombre: "Perdón",
    keywords: ["perdón","perdonar","rencor","resentimiento","ofensa","reconciliación"],
    referencias: [
      { libro: "Mateo", capitulo: 6, versiculo: 14 },
      { libro: "Efesios", capitulo: 4, versiculo: 32 },
      { libro: "Colosenses", capitulo: 3, versiculo: 13 },
      { libro: "Mateo", capitulo: 18, versiculo: 21 },
      { libro: "Lucas", capitulo: 6, versiculo: 37 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Isaías", capitulo: 43, versiculo: 25 },
      { libro: "Mateo", capitulo: 5, versiculo: 23 },
      { libro: "Marcos", capitulo: 11, versiculo: 25 },
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 32, versiculo: 1 },
      { libro: "Romanos", capitulo: 12, versiculo: 19 },
      { libro: "Salmos", capitulo: 130, versiculo: 4 },
      { libro: "Lucas", capitulo: 23, versiculo: 34 },
      { libro: "Salmos", capitulo: 79, versiculo: 9 },
      { libro: "Proverbios", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 86, versiculo: 5 },
      { libro: "Hechos", capitulo: 7, versiculo: 60 },
      { libro: "Salmos", capitulo: 25, versiculo: 18 },
      { libro: "Mateo", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 51, versiculo: 9 },
      { libro: "2 Corintios", capitulo: 2, versiculo: 7 },
      { libro: "Salmos", capitulo: 65, versiculo: 3 },
      { libro: "Génesis", capitulo: 50, versiculo: 17 },
      { libro: "Salmos", capitulo: 99, versiculo: 8 },
      { libro: "Lucas", capitulo: 17, versiculo: 4 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Efesios", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 34, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 85, versiculo: 2 },
      { libro: "Colosenses", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 107, versiculo: 17 }
    ],
    fraseEmpatica: [
      "Si perdonáis a otros sus ofensas, vuestro Padre celestial también os perdonará a vosotros.",
      "Sed bondadosos y compasivos unos con otros, perdonándoos mutuamente.",
      "Soportándoos unos a otros y perdonándoos si alguno tiene queja contra otro.",
      "No te digo hasta siete veces, sino hasta setenta veces siete.",
      "Perdonad, y seréis perdonados.",
      "El perdón no justifica al ofensor, te libera a ti.",
      "Perdonar es soltar el veneno que llevas dentro.",
      "Dios te perdonó una deuda impagable; ¿no perdonarás tú la pequeña ofensa?",
      "El perdón es el idioma del cielo.",
      "Padre, perdónalos, porque no saben lo que hacen."
    ]
  },
  {
    nombre: "Tentación / Pecado",
    keywords: ["tentación","pecado","caer","error","vicio","lucha"],
    referencias: [
      { libro: "1 Corintios", capitulo: 10, versiculo: 13 },
      { libro: "Mateo", capitulo: 26, versiculo: 41 },
      { libro: "Santiago", capitulo: 1, versiculo: 12 },
      { libro: "Salmos", capitulo: 119, versiculo: 11 },
      { libro: "Hebreos", capitulo: 2, versiculo: 18 },
      { libro: "Salmos", capitulo: 19, versiculo: 13 },
      { libro: "Gálatas", capitulo: 6, versiculo: 1 },
      { libro: "Salmos", capitulo: 39, versiculo: 1 },
      { libro: "2 Pedro", capitulo: 2, versiculo: 9 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "Romanos", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 141, versiculo: 4 },
      { libro: "Lucas", capitulo: 22, versiculo: 40 },
      { libro: "Salmos", capitulo: 17, versiculo: 4 },
      { libro: "Efesios", capitulo: 6, versiculo: 13 },
      { libro: "Salmos", capitulo: 119, versiculo: 9 },
      { libro: "1 Juan", capitulo: 2, versiculo: 16 },
      { libro: "Salmos", capitulo: 38, versiculo: 1 },
      { libro: "Mateo", capitulo: 4, versiculo: 10 },
      { libro: "Salmos", capitulo: 130, versiculo: 3 },
      { libro: "Proverbios", capitulo: 4, versiculo: 23 },
      { libro: "Salmos", capitulo: 25, versiculo: 15 },
      { libro: "Romanos", capitulo: 7, versiculo: 24 },
      { libro: "Salmos", capitulo: 119, versiculo: 133 },
      { libro: "Tito", capitulo: 2, versiculo: 12 },
      { libro: "Salmos", capitulo: 44, versiculo: 21 },
      { libro: "Hebreos", capitulo: 4, versiculo: 15 },
      { libro: "Salmos", capitulo: 139, versiculo: 23 },
      { libro: "Santiago", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 90, versiculo: 8 },
      { libro: "1 Timoteo", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 18, versiculo: 23 },
      { libro: "Apocalipsis", capitulo: 3, versiculo: 10 }
    ],
    fraseEmpatica: [
      "No os ha sobrevenido ninguna tentación que no sea humana; pero fiel es Dios, que no os dejará ser tentados más de lo que podéis resistir.",
      "Velad y orad para que no entréis en tentación.",
      "Bienaventurado el hombre que soporta la tentación.",
      "En mi corazón he guardado tus dichos para no pecar contra ti.",
      "Resistid al diablo y huirá de vosotros.",
      "La tentación no es pecado; lo es ceder a ella. Hoy puedes vencer.",
      "No estás solo en esta lucha; millones de ángeles pelean contigo.",
      "Cada 'no' a la tentación es un 'sí' a la libertad.",
      "Dios no te juzga por sentir la tentación, sino por cómo respondes a ella.",
      "Eres más fuerte de lo que crees; el que está en ti es mayor."
    ]
  },
  {
    nombre: "Familia / Hogar",
    keywords: ["familia","hogar","hijo","padres","esposo","matrimonio","casa"],
    referencias: [
      { libro: "Josué", capitulo: 24, versiculo: 15 },
      { libro: "Salmos", capitulo: 127, versiculo: 1 },
      { libro: "Proverbios", capitulo: 22, versiculo: 6 },
      { libro: "Efesios", capitulo: 6, versiculo: 1 },
      { libro: "Salmos", capitulo: 128, versiculo: 3 },
      { libro: "Colosenses", capitulo: 3, versiculo: 20 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "1 Timoteo", capitulo: 5, versiculo: 8 },
      { libro: "Salmos", capitulo: 103, versiculo: 17 },
      { libro: "Mateo", capitulo: 19, versiculo: 5 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Génesis", capitulo: 2, versiculo: 24 },
      { libro: "Salmos", capitulo: 127, versiculo: 3 },
      { libro: "Proverbios", capitulo: 1, versiculo: 8 },
      { libro: "Salmos", capitulo: 112, versiculo: 2 },
      { libro: "Deuteronomio", capitulo: 6, versiculo: 7 },
      { libro: "Salmos", capitulo: 78, versiculo: 6 },
      { libro: "Efesios", capitulo: 5, versiculo: 25 },
      { libro: "Salmos", capitulo: 144, versiculo: 12 },
      { libro: "Isaías", capitulo: 54, versiculo: 13 },
      { libro: "Salmos", capitulo: 34, versiculo: 11 },
      { libro: "Tito", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 128, versiculo: 6 },
      { libro: "Hebreos", capitulo: 13, versiculo: 4 },
      { libro: "Salmos", capitulo: 115, versiculo: 14 },
      { libro: "Lucas", capitulo: 15, versiculo: 20 },
      { libro: "Salmos", capitulo: 145, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 3, versiculo: 7 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Proverbios", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 91, versiculo: 9 },
      { libro: "Malaquías", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 }
    ],
    fraseEmpatica: [
      "Yo y mi casa serviremos al Señor.",
      "Si el Señor no edifica la casa, en vano trabajan los que la edifican.",
      "Instruye al niño en su camino, y aun cuando fuere viejo no se apartará de él.",
      "Hijos, obedeced en el Señor a vuestros padres, porque esto es justo.",
      "Tu esposa será como vid fecunda en el interior de tu casa.",
      "La familia es el primer templo donde aprendemos a amar.",
      "Dios habita en medio de tu hogar; no hay rincón sin su presencia.",
      "Cada comida en familia es una eucaristía cotidiana.",
      "Ama a los tuyos como Cristo amó a su Iglesia: entregándose.",
      "Bendice, Señor, nuestro hogar y hazlo reflejo de tu amor."
    ]
  },
  {
    nombre: "Amor de Dios",
    keywords: ["amor de Dios","amor divino","Dios me ama","amor eterno"],
    referencias: [
      { libro: "Juan", capitulo: 3, versiculo: 16 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "1 Juan", capitulo: 4, versiculo: 9 },
      { libro: "Jeremías", capitulo: 31, versiculo: 3 },
      { libro: "Salmos", capitulo: 136, versiculo: 26 },
      { libro: "Efesios", capitulo: 2, versiculo: 4 },
      { libro: "1 Juan", capitulo: 4, versiculo: 16 },
      { libro: "Salmos", capitulo: 103, versiculo: 8 },
      { libro: "Romanos", capitulo: 5, versiculo: 8 },
      { libro: "Sofonías", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 86, versiculo: 15 },
      { libro: "1 Juan", capitulo: 3, versiculo: 1 },
      { libro: "Salmos", capitulo: 63, versiculo: 3 },
      { libro: "Juan", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 36, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 35 },
      { libro: "Salmos", capitulo: 103, versiculo: 11 },
      { libro: "Isaías", capitulo: 54, versiculo: 10 },
      { libro: "Salmos", capitulo: 52, versiculo: 8 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 22 },
      { libro: "Salmos", capitulo: 59, versiculo: 16 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 9 },
      { libro: "Salmos", capitulo: 23, versiculo: 6 },
      { libro: "1 Corintios", capitulo: 13, versiculo: 7 },
      { libro: "Salmos", capitulo: 143, versiculo: 8 },
      { libro: "Juan", capitulo: 17, versiculo: 26 },
      { libro: "Salmos", capitulo: 139, versiculo: 17 },
      { libro: "Apocalipsis", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 109, versiculo: 21 },
      { libro: "Oseas", capitulo: 11, versiculo: 4 },
      { libro: "Salmos", capitulo: 32, versiculo: 10 },
      { libro: "1 Juan", capitulo: 4, versiculo: 10 },
      { libro: "Salmos", capitulo: 145, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Porque de tal manera amó Dios al mundo que ha dado a su Hijo unigénito.",
      "Ni la muerte ni la vida podrán separarnos del amor de Dios.",
      "En esto se mostró el amor de Dios para con nosotros: en que envió a su Hijo.",
      "Con amor eterno te he amado.",
      "Dios es amor, y el que permanece en amor permanece en Dios.",
      "Su amor no depende de lo que tú hagas, sino de quién es Él.",
      "Eres amado sin condiciones, sin límites, sin fecha de caducidad.",
      "Antes de que nacieras, Dios ya te amaba.",
      "El amor divino no se gana; se recibe.",
      "Dios te mira con ternura infinita, como un padre a su hijo pequeño."
    ]
  },
  {
    nombre: "Amor al prójimo",
    keywords: ["amor al prójimo","caridad","ayudar","servicio","compartir"],
    referencias: [
      { libro: "Mateo", capitulo: 22, versiculo: 39 },
      { libro: "Juan", capitulo: 13, versiculo: 34 },
      { libro: "1 Juan", capitulo: 4, versiculo: 20 },
      { libro: "Lucas", capitulo: 6, versiculo: 31 },
      { libro: "Romanos", capitulo: 13, versiculo: 10 },
      { libro: "1 Corintios", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 41, versiculo: 1 },
      { libro: "Proverbios", capitulo: 19, versiculo: 17 },
      { libro: "Mateo", capitulo: 25, versiculo: 40 },
      { libro: "Gálatas", capitulo: 6, versiculo: 2 },
      { libro: "Salmos", capitulo: 112, versiculo: 9 },
      { libro: "Hebreos", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 82, versiculo: 3 },
      { libro: "Santiago", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 21 },
      { libro: "Lucas", capitulo: 10, versiculo: 30 },
      { libro: "Salmos", capitulo: 146, versiculo: 9 },
      { libro: "1 Juan", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 140, versiculo: 12 },
      { libro: "Mateo", capitulo: 5, versiculo: 42 },
      { libro: "Salmos", capitulo: 72, versiculo: 12 },
      { libro: "Deuteronomio", capitulo: 15, versiculo: 11 },
      { libro: "Salmos", capitulo: 34, versiculo: 14 },
      { libro: "Lucas", capitulo: 14, versiculo: 13 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "Filipenses", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 10, versiculo: 17 },
      { libro: "1 Pedro", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 112, versiculo: 5 },
      { libro: "Proverbios", capitulo: 21, versiculo: 13 },
      { libro: "Salmos", capitulo: 15, versiculo: 3 },
      { libro: "Romanos", capitulo: 12, versiculo: 15 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 }
    ],
    fraseEmpatica: [
      "Amarás a tu prójimo como a ti mismo.",
      "Un mandamiento nuevo os doy: que os améis unos a otros.",
      "El amor es paciente, es bondadoso. El amor no es envidioso.",
      "Todo lo que hicisteis por uno de estos mis hermanos más pequeños, por mí lo hicisteis.",
      "Sobrellevad los unos las cargas de los otros.",
      "Cada acto de bondad es una semilla que florece en el cielo.",
      "En el rostro del necesitado, Cristo te mira.",
      "El amor no se dice, se demuestra.",
      "Hoy puedes ser el ángel que alguien necesita.",
      "Compartir es multiplicar la alegría."
    ]
  },
  {
    nombre: "Amistad",
    keywords: ["amistad","amigo","compañero","confidente","lealtad"],
    referencias: [
      { libro: "Proverbios", capitulo: 17, versiculo: 17 },
      { libro: "Juan", capitulo: 15, versiculo: 13 },
      { libro: "Proverbios", capitulo: 18, versiculo: 24 },
      { libro: "Eclesiastés", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "Proverbios", capitulo: 27, versiculo: 6 },
      { libro: "Job", capitulo: 6, versiculo: 14 },
      { libro: "Salmos", capitulo: 35, versiculo: 14 },
      { libro: "Proverbios", capitulo: 27, versiculo: 9 },
      { libro: "1 Samuel", capitulo: 18, versiculo: 1 },
      { libro: "Salmos", capitulo: 88, versiculo: 18 },
      { libro: "Proverbios", capitulo: 27, versiculo: 17 },
      { libro: "Lucas", capitulo: 11, versiculo: 5 },
      { libro: "Salmos", capitulo: 55, versiculo: 13 },
      { libro: "Job", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 41, versiculo: 9 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 33 },
      { libro: "Salmos", capitulo: 119, versiculo: 63 },
      { libro: "Santiago", capitulo: 2, versiculo: 23 },
      { libro: "Salmos", capitulo: 31, versiculo: 11 },
      { libro: "Proverbios", capitulo: 22, versiculo: 24 },
      { libro: "Salmos", capitulo: 38, versiculo: 11 },
      { libro: "Eclesiástico", capitulo: 6, versiculo: 14 },
      { libro: "Salmos", capitulo: 109, versiculo: 4 },
      { libro: "Juan", capitulo: 11, versiculo: 35 },
      { libro: "Salmos", capitulo: 142, versiculo: 4 },
      { libro: "Proverbios", capitulo: 17, versiculo: 9 },
      { libro: "Salmos", capitulo: 25, versiculo: 14 },
      { libro: "Romanos", capitulo: 12, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 9 },
      { libro: "Colosenses", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 11 }
    ],
    fraseEmpatica: [
      "En todo tiempo ama el amigo, y es como un hermano en la adversidad.",
      "Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.",
      "Hay amigos que llevan a la ruina, pero hay amigos más fieles que un hermano.",
      "Mejores son dos que uno, porque tienen mejor paga de su trabajo.",
      "Hierro con hierro se aguza, y el hombre aguza el rostro de su amigo.",
      "Un amigo fiel es un refugio seguro; quien lo encuentra, encuentra un tesoro.",
      "La amistad verdadera es un rayo del amor de Dios en la tierra.",
      "Cultiva tus amistades, son jardines que florecen en el desierto.",
      "Un amigo no juzga tus caídas, sino que te ayuda a levantarte.",
      "Donde hay un amigo, hay un pedacito de cielo."
    ]
  },
  {
    nombre: "Gratitud / Acción de gracias",
    keywords: ["gratitud","gracias","agradecimiento","bendición","dar gracias"],
    referencias: [
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 18 },
      { libro: "Salmos", capitulo: 100, versiculo: 4 },
      { libro: "Colosenses", capitulo: 3, versiculo: 15 },
      { libro: "Salmos", capitulo: 136, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 118, versiculo: 1 },
      { libro: "Efesios", capitulo: 5, versiculo: 20 },
      { libro: "Salmos", capitulo: 107, versiculo: 1 },
      { libro: "Lucas", capitulo: 17, versiculo: 16 },
      { libro: "Salmos", capitulo: 95, versiculo: 2 },
      { libro: "2 Corintios", capitulo: 9, versiculo: 15 },
      { libro: "Salmos", capitulo: 50, versiculo: 14 },
      { libro: "Daniel", capitulo: 2, versiculo: 23 },
      { libro: "Salmos", capitulo: 103, versiculo: 2 },
      { libro: "Juan", capitulo: 6, versiculo: 11 },
      { libro: "Salmos", capitulo: 75, versiculo: 1 },
      { libro: "Apocalipsis", capitulo: 11, versiculo: 17 },
      { libro: "Salmos", capitulo: 116, versiculo: 12 },
      { libro: "Hechos", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Romanos", capitulo: 1, versiculo: 21 },
      { libro: "Salmos", capitulo: 34, versiculo: 1 },
      { libro: "1 Crónicas", capitulo: 16, versiculo: 34 },
      { libro: "Salmos", capitulo: 138, versiculo: 1 },
      { libro: "Colosenses", capitulo: 2, versiculo: 7 },
      { libro: "Salmos", capitulo: 30, versiculo: 12 },
      { libro: "Lucas", capitulo: 22, versiculo: 19 },
      { libro: "Salmos", capitulo: 7, versiculo: 17 },
      { libro: "Isaías", capitulo: 12, versiculo: 4 },
      { libro: "Salmos", capitulo: 69, versiculo: 30 },
      { libro: "Hebreos", capitulo: 12, versiculo: 28 },
      { libro: "Salmos", capitulo: 145, versiculo: 10 },
      { libro: "Jonás", capitulo: 2, versiculo: 9 }
    ],
    fraseEmpatica: [
      "Dad gracias en todo, porque esta es la voluntad de Dios.",
      "Entrad por sus puertas con acción de gracias, por sus atrios con alabanza.",
      "Sed agradecidos.",
      "Dad gracias al Señor, porque Él es bueno; para siempre es su misericordia.",
      "Bendice, alma mía, al Señor, y no olvides ninguno de sus beneficios.",
      "La gratitud es la memoria del corazón.",
      "Cada pequeño don es una muestra del amor infinito de Dios.",
      "Hoy es un buen día para contar bendiciones en lugar de penas.",
      "El corazón agradecido atrae milagros.",
      "Gracias, Señor, por el aire, por el sol, por la vida."
    ]
  },
  {
    nombre: "Alegría / Gozo",
    keywords: ["alegría","gozo","felicidad","contento","júbilo","regocijo"],
    referencias: [
      { libro: "Salmos", capitulo: 118, versiculo: 24 },
      { libro: "Filipenses", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 16, versiculo: 11 },
      { libro: "Nehemías", capitulo: 8, versiculo: 10 },
      { libro: "Salmos", capitulo: 30, versiculo: 11 },
      { libro: "Proverbios", capitulo: 17, versiculo: 22 },
      { libro: "Salmos", capitulo: 126, versiculo: 2 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 32, versiculo: 11 },
      { libro: "Gálatas", capitulo: 5, versiculo: 22 },
      { libro: "Salmos", capitulo: 5, versiculo: 11 },
      { libro: "Lucas", capitulo: 10, versiculo: 21 },
      { libro: "Salmos", capitulo: 33, versiculo: 1 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 97, versiculo: 12 },
      { libro: "Isaías", capitulo: 35, versiculo: 10 },
      { libro: "Salmos", capitulo: 149, versiculo: 2 },
      { libro: "Juan", capitulo: 15, versiculo: 11 },
      { libro: "Salmos", capitulo: 68, versiculo: 3 },
      { libro: "Proverbios", capitulo: 10, versiculo: 28 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "Habacuc", capitulo: 3, versiculo: 18 },
      { libro: "Salmos", capitulo: 4, versiculo: 7 },
      { libro: "Hechos", capitulo: 16, versiculo: 34 },
      { libro: "Salmos", capitulo: 126, versiculo: 5 },
      { libro: "Mateo", capitulo: 2, versiculo: 10 },
      { libro: "Salmos", capitulo: 64, versiculo: 10 },
      { libro: "Sofonías", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 90, versiculo: 14 },
      { libro: "Filipenses", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 21, versiculo: 1 },
      { libro: "1 Juan", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 43, versiculo: 4 }
    ],
    fraseEmpatica: [
      "Este es el día que hizo el Señor; nos gozaremos y alegraremos en él.",
      "Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!",
      "En tu presencia hay plenitud de gozo.",
      "El gozo del Señor es vuestra fortaleza.",
      "Has cambiado mi lamento en baile.",
      "La alegría es el idioma del cielo.",
      "Dios baila de alegría cuando ve feliz a un hijo suyo.",
      "El corazón alegre es una buena medicina.",
      "Deja que la luz de Dios disipe cualquier sombra de tristeza.",
      "Hoy el cielo se viste de fiesta contigo."
    ]
  },
  {
    nombre: "Paciencia / Perseverancia",
    keywords: ["paciencia","perseverancia","constancia","esperar","resistencia","aguante"],
    referencias: [
      { libro: "Romanos", capitulo: 12, versiculo: 12 },
      { libro: "Santiago", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Hebreos", capitulo: 10, versiculo: 36 },
      { libro: "Proverbios", capitulo: 14, versiculo: 29 },
      { libro: "Salmos", capitulo: 40, versiculo: 1 },
      { libro: "2 Pedro", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Gálatas", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 9 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 26 },
      { libro: "Salmos", capitulo: 130, versiculo: 5 },
      { libro: "Romanos", capitulo: 8, versiculo: 25 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Colosenses", capitulo: 1, versiculo: 11 },
      { libro: "Salmos", capitulo: 25, versiculo: 3 },
      { libro: "Isaías", capitulo: 30, versiculo: 18 },
      { libro: "Salmos", capitulo: 33, versiculo: 20 },
      { libro: "Santiago", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 84 },
      { libro: "Mateo", capitulo: 24, versiculo: 13 },
      { libro: "Salmos", capitulo: 71, versiculo: 14 },
      { libro: "Apocalipsis", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 37, versiculo: 34 },
      { libro: "1 Tesalonicenses", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 92, versiculo: 12 },
      { libro: "Hebreos", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 52, versiculo: 9 },
      { libro: "Lucas", capitulo: 8, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 5 },
      { libro: "Romanos", capitulo: 5, versiculo: 3 },
      { libro: "Salmos", capitulo: 69, versiculo: 13 },
      { libro: "Filipenses", capitulo: 3, versiculo: 14 }
    ],
    fraseEmpatica: [
      "Gozosos en la esperanza, pacientes en la tribulación, constantes en la oración.",
      "La paciencia produce carácter probado.",
      "Guarda silencio ante el Señor y espera en Él con paciencia.",
      "No os canséis de hacer el bien, porque a su tiempo segaréis.",
      "El que persevere hasta el fin será salvo.",
      "Dios nunca llega tarde; sus tiempos son perfectos.",
      "La espera no es tiempo perdido, es tiempo de preparación.",
      "Cada día de espera es un peldaño hacia tu bendición.",
      "La paciencia es la llave que abre puertas invisibles.",
      "Confía, respira, espera. Dios está obrando en silencio."
    ]
  },
  {
    nombre: "Humildad",
    keywords: ["humildad","sencillez","mansedumbre","pequeñez","no orgullo"],
    referencias: [
      { libro: "Mateo", capitulo: 23, versiculo: 12 },
      { libro: "Santiago", capitulo: 4, versiculo: 10 },
      { libro: "Proverbios", capitulo: 22, versiculo: 4 },
      { libro: "Miqueas", capitulo: 6, versiculo: 8 },
      { libro: "Salmos", capitulo: 25, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 6 },
      { libro: "Salmos", capitulo: 149, versiculo: 4 },
      { libro: "Filipenses", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 131, versiculo: 1 },
      { libro: "Efesios", capitulo: 4, versiculo: 2 },
      { libro: "Salmos", capitulo: 138, versiculo: 6 },
      { libro: "Colosenses", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Mateo", capitulo: 11, versiculo: 29 },
      { libro: "Salmos", capitulo: 34, versiculo: 2 },
      { libro: "Romanos", capitulo: 12, versiculo: 3 },
      { libro: "Salmos", capitulo: 147, versiculo: 6 },
      { libro: "Lucas", capitulo: 14, versiculo: 11 },
      { libro: "Salmos", capitulo: 113, versiculo: 6 },
      { libro: "Proverbios", capitulo: 29, versiculo: 23 },
      { libro: "Salmos", capitulo: 18, versiculo: 27 },
      { libro: "Isaías", capitulo: 66, versiculo: 2 },
      { libro: "Salmos", capitulo: 119, versiculo: 21 },
      { libro: "2 Crónicas", capitulo: 7, versiculo: 14 },
      { libro: "Salmos", capitulo: 10, versiculo: 17 },
      { libro: "Sofonías", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 37, versiculo: 11 },
      { libro: "Mateo", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 76, versiculo: 9 },
      { libro: "Daniel", capitulo: 10, versiculo: 12 },
      { libro: "Salmos", capitulo: 86, versiculo: 1 },
      { libro: "Lucas", capitulo: 1, versiculo: 52 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 }
    ],
    fraseEmpatica: [
      "El que se enaltece será humillado, y el que se humilla será enaltecido.",
      "Humillaos delante del Señor y Él os exaltará.",
      "El temor del Señor es enseñanza de sabiduría, y la humildad precede a la honra.",
      "Oh hombre, Él te ha declarado lo que es bueno: hacer justicia, amar misericordia y humillarte ante tu Dios.",
      "Aprended de mí, que soy manso y humilde de corazón.",
      "La grandeza ante Dios se mide por la pequeñez ante los hombres.",
      "Ser humilde no es pensar menos de ti, sino pensar menos en ti.",
      "Dios resiste a los soberbios, pero da gracia a los humildes.",
      "En el silencio humilde, Dios susurra sus secretos.",
      "El que se arrodilla ante Dios puede estar de pie ante cualquier hombre."
    ]
  },
  {
    nombre: "Sabiduría / Discernimiento",
    keywords: ["sabiduría","discernimiento","entendimiento","inteligencia","prudencia","consejo"],
    referencias: [
      { libro: "Santiago", capitulo: 1, versiculo: 5 },
      { libro: "Proverbios", capitulo: 2, versiculo: 6 },
      { libro: "Salmos", capitulo: 111, versiculo: 10 },
      { libro: "Proverbios", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 105 },
      { libro: "1 Reyes", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 19, versiculo: 7 },
      { libro: "Proverbios", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 90, versiculo: 12 },
      { libro: "Efesios", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 66 },
      { libro: "Colosenses", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "Isaías", capitulo: 11, versiculo: 2 },
      { libro: "Salmos", capitulo: 25, versiculo: 12 },
      { libro: "Proverbios", capitulo: 16, versiculo: 16 },
      { libro: "Salmos", capitulo: 37, versiculo: 30 },
      { libro: "Daniel", capitulo: 2, versiculo: 21 },
      { libro: "Salmos", capitulo: 119, versiculo: 98 },
      { libro: "1 Corintios", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 51, versiculo: 6 },
      { libro: "Proverbios", capitulo: 11, versiculo: 2 },
      { libro: "Salmos", capitulo: 107, versiculo: 43 },
      { libro: "Romanos", capitulo: 11, versiculo: 33 },
      { libro: "Salmos", capitulo: 139, versiculo: 6 },
      { libro: "Proverbios", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 104, versiculo: 24 },
      { libro: "Eclesiastés", capitulo: 2, versiculo: 26 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Job", capitulo: 12, versiculo: 13 },
      { libro: "Salmos", capitulo: 136, versiculo: 5 },
      { libro: "Isaías", capitulo: 40, versiculo: 28 },
      { libro: "Salmos", capitulo: 147, versiculo: 5 }
    ],
    fraseEmpatica: [
      "Si alguno de vosotros tiene falta de sabiduría, pídala a Dios, el cual da a todos abundantemente.",
      "El principio de la sabiduría es el temor del Señor.",
      "Sabiduría ante todo; adquiere sabiduría, y sobre todas tus posesiones adquiere inteligencia.",
      "Lámpara es a mis pies tu palabra y lumbrera a mi camino.",
      "Enséñanos a contar nuestros días de tal manera que traigamos al corazón sabiduría.",
      "La verdadera sabiduría no está en saber mucho, sino en amar mucho.",
      "Dios no te pide que tengas todas las respuestas, solo que confíes en quien las tiene.",
      "Ante una decisión difícil, cierra los ojos y pregunta: ¿qué haría el amor?",
      "El discernimiento es la brújula del alma.",
      "Más vale un gramo de sabiduría divina que una tonelada de inteligencia humana."
    ]
  },
  {
    nombre: "Trabajo / Desempleo",
    keywords: ["trabajo","empleo","desempleo","paro","profesión","oficio","negocio"],
    referencias: [
      { libro: "Colosenses", capitulo: 3, versiculo: 23 },
      { libro: "Proverbios", capitulo: 16, versiculo: 3 },
      { libro: "Salmos", capitulo: 90, versiculo: 17 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 10 },
      { libro: "Proverbios", capitulo: 12, versiculo: 11 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 },
      { libro: "Eclesiastés", capitulo: 9, versiculo: 10 },
      { libro: "Proverbios", capitulo: 14, versiculo: 23 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "1 Timoteo", capitulo: 5, versiculo: 18 },
      { libro: "Salmos", capitulo: 104, versiculo: 23 },
      { libro: "Proverbios", capitulo: 22, versiculo: 29 },
      { libro: "Salmos", capitulo: 34, versiculo: 10 },
      { libro: "Mateo", capitulo: 25, versiculo: 21 },
      { libro: "Salmos", capitulo: 127, versiculo: 1 },
      { libro: "Génesis", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 112, versiculo: 3 },
      { libro: "Proverbios", capitulo: 10, versiculo: 4 },
      { libro: "Salmos", capitulo: 145, versiculo: 15 },
      { libro: "Efesios", capitulo: 4, versiculo: 28 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Deuteronomio", capitulo: 8, versiculo: 18 },
      { libro: "Salmos", capitulo: 1, versiculo: 3 },
      { libro: "Lucas", capitulo: 10, versiculo: 7 },
      { libro: "Salmos", capitulo: 25, versiculo: 12 },
      { libro: "Proverbios", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 4 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 58 },
      { libro: "Salmos", capitulo: 115, versiculo: 12 },
      { libro: "Proverbios", capitulo: 28, versiculo: 19 },
      { libro: "Salmos", capitulo: 132, versiculo: 15 },
      { libro: "Isaías", capitulo: 65, versiculo: 21 },
      { libro: "Salmos", capitulo: 128, versiculo: 1 }
    ],
    fraseEmpatica: [
      "Todo lo que hagáis, hacedlo de corazón, como para el Señor.",
      "Encomienda al Señor tus obras, y tus pensamientos serán afirmados.",
      "Confirma, Señor, la obra de nuestras manos.",
      "El que no trabaja, que no coma.",
      "El trabajo es un don, no un castigo.",
      "Dios es el mejor jefe que puedas tener; confía en sus tiempos.",
      "Cada labor, por humilde que parezca, es un escalón hacia tu propósito.",
      "No te desanimes si hoy no ves fruto; la cosecha llegará.",
      "Dios proveerá el pan, pero quiere que amases la harina.",
      "Bienaventurado el que come del trabajo de sus manos."
    ]
  },
  {
    nombre: "Estudios / Exámenes",
    keywords: ["estudios","examen","estudiar","aprender","prueba","conocimiento"],
    referencias: [
      { libro: "Proverbios", capitulo: 1, versiculo: 7 },
      { libro: "Santiago", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 119, versiculo: 99 },
      { libro: "Proverbios", capitulo: 9, versiculo: 10 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "2 Timoteo", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 119, versiculo: 66 },
      { libro: "Proverbios", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 25, versiculo: 4 },
      { libro: "Daniel", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 34 },
      { libro: "Colosenses", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 30 },
      { libro: "1 Reyes", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 119, versiculo: 73 },
      { libro: "Proverbios", capitulo: 4, versiculo: 5 },
      { libro: "Salmos", capitulo: 94, versiculo: 10 },
      { libro: "Efesios", capitulo: 1, versiculo: 18 },
      { libro: "Salmos", capitulo: 16, versiculo: 7 },
      { libro: "Lucas", capitulo: 2, versiculo: 52 },
      { libro: "Salmos", capitulo: 71, versiculo: 17 },
      { libro: "Isaías", capitulo: 50, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 9 },
      { libro: "Proverbios", capitulo: 16, versiculo: 16 },
      { libro: "Salmos", capitulo: 49, versiculo: 3 },
      { libro: "Mateo", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 27 },
      { libro: "1 Corintios", capitulo: 8, versiculo: 1 },
      { libro: "Salmos", capitulo: 78, versiculo: 72 },
      { libro: "Proverbios", capitulo: 18, versiculo: 15 },
      { libro: "Salmos", capitulo: 138, versiculo: 3 },
      { libro: "Jeremías", capitulo: 33, versiculo: 3 },
      { libro: "Salmos", capitulo: 143, versiculo: 10 }
    ],
    fraseEmpatica: [
      "El principio de la sabiduría es el temor del Señor.",
      "Si alguno tiene falta de sabiduría, pídala a Dios.",
      "Más que todos mis maestros he entendido, porque tus testimonios son mi meditación.",
      "Procura con diligencia presentarte a Dios aprobado, como obrero que no tiene de qué avergonzarse.",
      "Aún no ha llegado el examen final; confía en el Maestro.",
      "Estudia con fe, porque el conocimiento sin amor de Dios es vacío.",
      "Dios te ha dado inteligencia; úsala para su gloria.",
      "Ante un examen, respira y recuerda: no estás solo, el Espíritu Santo te guía.",
      "La verdadera sabiduría es saber que todo lo bueno viene de Dios.",
      "Hoy estudias; mañana enseñas. Todo es parte de su plan."
    ]
  },
  {
    nombre: "Ayuda económica / Providencia",
    keywords: ["dinero","deuda","económico","pobreza","necesidad","provisión"],
    referencias: [
      { libro: "Filipenses", capitulo: 4, versiculo: 19 },
      { libro: "Salmos", capitulo: 23, versiculo: 1 },
      { libro: "Mateo", capitulo: 6, versiculo: 26 },
      { libro: "Salmos", capitulo: 34, versiculo: 10 },
      { libro: "Proverbios", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Malaquías", capitulo: 3, versiculo: 10 },
      { libro: "Salmos", capitulo: 112, versiculo: 3 },
      { libro: "2 Corintios", capitulo: 9, versiculo: 8 },
      { libro: "Salmos", capitulo: 132, versiculo: 15 },
      { libro: "Lucas", capitulo: 12, versiculo: 24 },
      { libro: "Salmos", capitulo: 145, versiculo: 16 },
      { libro: "Deuteronomio", capitulo: 28, versiculo: 12 },
      { libro: "Salmos", capitulo: 104, versiculo: 28 },
      { libro: "1 Timoteo", capitulo: 6, versiculo: 17 },
      { libro: "Salmos", capitulo: 107, versiculo: 9 },
      { libro: "Proverbios", capitulo: 11, versiculo: 24 },
      { libro: "Salmos", capitulo: 37, versiculo: 19 },
      { libro: "Éxodo", capitulo: 16, versiculo: 4 },
      { libro: "Salmos", capitulo: 84, versiculo: 11 },
      { libro: "Mateo", capitulo: 7, versiculo: 11 },
      { libro: "Salmos", capitulo: 81, versiculo: 10 },
      { libro: "Santiago", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 127, versiculo: 2 },
      { libro: "Proverbios", capitulo: 22, versiculo: 7 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "1 Juan", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Génesis", capitulo: 22, versiculo: 14 },
      { libro: "Salmos", capitulo: 50, versiculo: 10 },
      { libro: "Lucas", capitulo: 6, versiculo: 38 },
      { libro: "Salmos", capitulo: 112, versiculo: 5 },
      { libro: "Proverbios", capitulo: 28, versiculo: 27 }
    ],
    fraseEmpatica: [
      "Mi Dios proveerá a todas vuestras necesidades conforme a sus riquezas en gloria en Cristo Jesús.",
      "El Señor es mi pastor, nada me falta.",
      "Mirad las aves del cielo… ¿No valéis vosotros mucho más que ellas?",
      "Los que buscan al Señor no carecen de ningún bien.",
      "Honra al Señor con tus bienes y tus graneros se llenarán.",
      "Dios es tu proveedor, no solo de dinero, sino de paz en la escasez.",
      "Cuando los recursos fallan, el milagro comienza.",
      "No mires la cartera vacía; mira al dueño del oro y de la plata.",
      "La providencia divina nunca llega tarde ni temprano; llega justo a tiempo.",
      "Confía: el que alimenta a los pájaros no dejará morir de hambre a sus hijos."
    ]
  },
  {
    nombre: "Justicia / Injusticia",
    keywords: ["justicia","injusticia","injusto","desigualdad","rectitud","juicio"],
    referencias: [
      { libro: "Miqueas", capitulo: 6, versiculo: 8 },
      { libro: "Isaías", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 82, versiculo: 3 },
      { libro: "Proverbios", capitulo: 21, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 28 },
      { libro: "Amós", capitulo: 5, versiculo: 24 },
      { libro: "Salmos", capitulo: 33, versiculo: 5 },
      { libro: "Lucas", capitulo: 18, versiculo: 7 },
      { libro: "Salmos", capitulo: 103, versiculo: 6 },
      { libro: "Deuteronomio", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 140, versiculo: 12 },
      { libro: "Romanos", capitulo: 12, versiculo: 19 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Isaías", capitulo: 61, versiculo: 8 },
      { libro: "Salmos", capitulo: 72, versiculo: 4 },
      { libro: "Jeremías", capitulo: 22, versiculo: 3 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Mateo", capitulo: 5, versiculo: 6 },
      { libro: "Salmos", capitulo: 11, versiculo: 7 },
      { libro: "Santiago", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 94, versiculo: 15 },
      { libro: "Proverbios", capitulo: 29, versiculo: 26 },
      { libro: "Salmos", capitulo: 58, versiculo: 11 },
      { libro: "Lucas", capitulo: 11, versiculo: 42 },
      { libro: "Salmos", capitulo: 99, versiculo: 4 },
      { libro: "Job", capitulo: 34, versiculo: 12 },
      { libro: "Salmos", capitulo: 45, versiculo: 6 },
      { libro: "Apocalipsis", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 119, versiculo: 137 },
      { libro: "Oseas", capitulo: 12, versiculo: 6 },
      { libro: "Salmos", capitulo: 75, versiculo: 2 },
      { libro: "2 Tesalonicenses", capitulo: 1, versiculo: 6 },
      { libro: "Salmos", capitulo: 98, versiculo: 9 }
    ],
    fraseEmpatica: [
      "Oh hombre, Él te ha declarado lo que es bueno: hacer justicia, amar misericordia y humillarte ante tu Dios.",
      "Aprended a hacer el bien, buscad el derecho, socorred al agraviado, haced justicia al huérfano, amparad a la viuda.",
      "Bienaventurados los que tienen hambre y sed de justicia, porque serán saciados.",
      "El Señor ama la justicia y no abandona a sus fieles.",
      "Mía es la venganza, yo pagaré, dice el Señor.",
      "La justicia humana falla; la divina nunca.",
      "Dios es el defensor del pobre y del oprimido.",
      "Aunque el mundo sea injusto, el Juez Supremo ve cada lágrima.",
      "No te canses de luchar por lo justo; Dios pelea contigo.",
      "La verdadera justicia comienza en un corazón que ama a Dios."
    ]
  },
  {
    nombre: "Esperanza en el futuro",
    keywords: ["esperanza","futuro","mañana","ilusión","visión","plan"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 33, versiculo: 22 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 71, versiculo: 5 },
      { libro: "Proverbios", capitulo: 23, versiculo: 18 },
      { libro: "Salmos", capitulo: 130, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 24 },
      { libro: "Salmos", capitulo: 39, versiculo: 7 },
      { libro: "Isaías", capitulo: 43, versiculo: 19 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Hebreos", capitulo: 11, versiculo: 1 },
      { libro: "Salmos", capitulo: 146, versiculo: 5 },
      { libro: "Jeremías", capitulo: 31, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 49 },
      { libro: "Tito", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 37, versiculo: 37 },
      { libro: "Miqueas", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Colosenses", capitulo: 1, versiculo: 27 },
      { libro: "Salmos", capitulo: 27, versiculo: 13 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 5 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "Zacarías", capitulo: 9, versiculo: 12 },
      { libro: "Salmos", capitulo: 84, versiculo: 11 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 17 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Romanos", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 121, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Porque yo sé los planes que tengo para vosotros, planes de bien y no de mal, para daros un futuro y una esperanza.",
      "El Dios de la esperanza os llene de todo gozo y paz en la fe.",
      "Los que esperan en el Señor renovarán sus fuerzas.",
      "Esta es mi porción, dice mi alma; por tanto, en Él esperaré.",
      "He aquí que yo hago algo nuevo; brotará ahora, ¿no lo notáis?",
      "Tu futuro es más brillante que tu pasado.",
      "Dios no te ha traído hasta aquí para abandonarte.",
      "Lo mejor está por venir.",
      "Cada mañana es una página en blanco que Dios escribe contigo.",
      "La esperanza cristiana no es un deseo, es una certeza."
    ]
  },
  {
    nombre: "Vocación / Propósito de vida",
    keywords: ["vocación","propósito","llamado","misión","sentido","para qué estoy aquí"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Efesios", capitulo: 2, versiculo: 10 },
      { libro: "Salmos", capitulo: 138, versiculo: 8 },
      { libro: "Romanos", capitulo: 8, versiculo: 28 },
      { libro: "Salmos", capitulo: 57, versiculo: 2 },
      { libro: "Proverbios", capitulo: 19, versiculo: 21 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "1 Corintios", capitulo: 7, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 4 },
      { libro: "Isaías", capitulo: 6, versiculo: 8 },
      { libro: "Salmos", capitulo: 16, versiculo: 11 },
      { libro: "Mateo", capitulo: 22, versiculo: 14 },
      { libro: "Salmos", capitulo: 25, versiculo: 14 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 9 },
      { libro: "Salmos", capitulo: 139, versiculo: 16 },
      { libro: "Juan", capitulo: 15, versiculo: 16 },
      { libro: "Salmos", capitulo: 119, versiculo: 35 },
      { libro: "Filipenses", capitulo: 3, versiculo: 14 },
      { libro: "Salmos", capitulo: 143, versiculo: 8 },
      { libro: "Gálatas", capitulo: 1, versiculo: 15 },
      { libro: "Salmos", capitulo: 40, versiculo: 8 },
      { libro: "2 Timoteo", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 27, versiculo: 11 },
      { libro: "Colosenses", capitulo: 1, versiculo: 16 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Hechos", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 100, versiculo: 3 },
      { libro: "Apocalipsis", capitulo: 17, versiculo: 14 },
      { libro: "Salmos", capitulo: 84, versiculo: 5 },
      { libro: "Lucas", capitulo: 1, versiculo: 79 },
      { libro: "Salmos", capitulo: 119, versiculo: 125 },
      { libro: "Romanos", capitulo: 12, versiculo: 6 },
      { libro: "Salmos", capitulo: 108, versiculo: 13 }
    ],
    fraseEmpatica: [
      "Antes de formarte en el vientre te conocí, y antes que nacieras te santifiqué.",
      "Somos hechura suya, creados en Cristo Jesús para buenas obras.",
      "El Señor cumplirá su propósito en mí.",
      "A los que aman a Dios, todas las cosas les ayudan a bien.",
      "Heme aquí, envíame a mí.",
      "No estás aquí por casualidad; Dios teje tu historia con hilos eternos.",
      "Tu vida tiene un propósito que solo tú puedes cumplir.",
      "Escucha el susurro divino que te llama por tu nombre.",
      "No busques grandes señales; a veces la vocación es amar lo que haces.",
      "Dios no te elige por tus capacidades, sino por tu disponibilidad."
    ]
  }
];

// ===== FUNCIONES DE BÚSQUEDA =====
function detectarCategoria(texto) {
  const textoLower = texto.toLowerCase();
  let mejorCategoria = null;
  let maxCoincidencias = 0;

  for (const categoria of categories) {
    let coincidencias = 0;
    for (const keyword of categoria.keywords) {
      if (textoLower.includes(keyword.toLowerCase())) {
        coincidencias++;
      }
    }
    if (coincidencias > maxCoincidencias) {
      maxCoincidencias = coincidencias;
      mejorCategoria = categoria;
    }
  }

  if (!mejorCategoria) {
    mejorCategoria = categories[Math.floor(Math.random() * categories.length)];
  }

  return mejorCategoria;
}

function obtenerTextoVersiculo(referencia) {
  try {
    for (const testamento in bibleData) {
      for (const libro in bibleData[testamento]) {
        if (libro.toLowerCase().includes(referencia.libro.toLowerCase())) {
          const capitulo = bibleData[testamento][libro][referencia.capitulo.toString()];
          if (capitulo && capitulo[referencia.versiculo.toString()]) {
            return capitulo[referencia.versiculo.toString()];
          }
        }
      }
    }
  } catch (e) {
    console.error("Error buscando versículo:", e);
  }
  return "El Señor es mi pastor, nada me falta.";
}
