// categories.js – Arcángel App (33 categorías completas con 33 referencias y 5 frases empáticas cada una)
const categories = [
  {
    nombre: "Miedo / Ansiedad",
    keywords: ["miedo","ansiedad","temor","angustia","preocupación","nervios","inquietud","susto","pánico","sobresalto"],
    referencias: [
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 56, versiculo: 4 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "Salmos", capitulo: 27, versiculo: 1 },
      { libro: "Josué", capitulo: 1, versiculo: 9 },
      { libro: "Mateo", capitulo: 6, versiculo: 34 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 34, versiculo: 5 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 118, versiculo: 6 },
      { libro: "Proverbios", capitulo: 29, versiculo: 25 },
      { libro: "Salmos", capitulo: 46, versiculo: 2 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 91, versiculo: 5 },
      { libro: "Lucas", capitulo: 12, versiculo: 25 },
      { libro: "Salmos", capitulo: 55, versiculo: 23 },
      { libro: "Salmos", capitulo: 112, versiculo: 7 },
      { libro: "Apocalipsis", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 56, versiculo: 12 },
      { libro: "Salmos", capitulo: 121, versiculo: 7 },
      { libro: "Isaías", capitulo: 35, versiculo: 4 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 15 },
      { libro: "Salmos", capitulo: 56, versiculo: 3 },
      { libro: "Proverbios", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 91, versiculo: 5 },
      { libro: "Isaías", capitulo: 54, versiculo: 4 },
      { libro: "Salmos", capitulo: 34, versiculo: 4 },
      { libro: "Lucas", capitulo: 12, versiculo: 7 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "Romanos", capitulo: 8, versiculo: 31 }
    ],
    fraseEmpatica: [
      "No temas, porque yo estoy contigo.",
      "El Señor está cerca de los quebrantados de corazón.",
      "Deposita tus preocupaciones en Él, que cuida de ti.",
      "La paz de Dios guardará tu corazón.",
      "Confía en el Señor y Él te sostendrá."
    ]
  },
  {
    nombre: "Tristeza / Pena",
    keywords: ["tristeza","pena","deprimido","abatido","desánimo","llanto","lágrimas","dolor emocional","melancolía","desconsuelo"],
    referencias: [
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Mateo", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 30, versiculo: 5 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Isaías", capitulo: 61, versiculo: 3 },
      { libro: "Salmos", capitulo: 126, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 22 },
      { libro: "Salmos", capitulo: 56, versiculo: 8 },
      { libro: "Juan", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 31, versiculo: 9 },
      { libro: "Romanos", capitulo: 12, versiculo: 15 },
      { libro: "Salmos", capitulo: 116, versiculo: 8 },
      { libro: "Isaías", capitulo: 53, versiculo: 4 },
      { libro: "Salmos", capitulo: 38, versiculo: 9 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 28 },
      { libro: "Jeremías", capitulo: 31, versiculo: 13 },
      { libro: "Salmos", capitulo: 34, versiculo: 6 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Juan", capitulo: 14, versiculo: 1 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Filipenses", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 43, versiculo: 5 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 10 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Hebreos", capitulo: 4, versiculo: 16 }
    ],
    fraseEmpatica: [
      "El Señor está cerca de los quebrantados de corazón.",
      "Tus lágrimas son recogidas por Aquel que te ama.",
      "El consuelo de Dios sobrepasa toda tristeza.",
      "No estás solo en tu dolor; Él camina a tu lado.",
      "La alegría vendrá por la mañana."
    ]
  },
  {
    nombre: "Estrés / Agobio",
    keywords: ["estrés","agobio","cansancio","sobrecarga","presión","agotamiento","burnout","tensión"],
    referencias: [
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Proverbios", capitulo: 3, versiculo: 5 },
      { libro: "Salmos", capitulo: 46, versiculo: 10 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 131, versiculo: 2 },
      { libro: "Lucas", capitulo: 10, versiculo: 41 },
      { libro: "Éxodo", capitulo: 33, versiculo: 14 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Isaías", capitulo: 26, versiculo: 3 },
      { libro: "Salmos", capitulo: 119, versiculo: 143 },
      { libro: "Romanos", capitulo: 8, versiculo: 6 },
      { libro: "Salmos", capitulo: 34, versiculo: 17 },
      { libro: "Mateo", capitulo: 6, versiculo: 34 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 },
      { libro: "Isaías", capitulo: 41, versiculo: 13 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Juan", capitulo: 16, versiculo: 33 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 8 },
      { libro: "Salmos", capitulo: 61, versiculo: 2 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 42, versiculo: 5 },
      { libro: "Marcos", capitulo: 6, versiculo: 31 },
      { libro: "Salmos", capitulo: 116, versiculo: 7 },
      { libro: "Lucas", capitulo: 12, versiculo: 25 }
    ],
    fraseEmpatica: [
      "Venid a mí los que estáis cansados y agobiados, y yo os haré descansar.",
      "No estás solo en esta carga; el Señor te sostiene.",
      "Deja tu ansiedad en sus manos, porque Él cuida de ti.",
      "La paz os dejo, mi paz os doy; no se turbe vuestro corazón.",
      "Los que confían en el Señor renovarán sus fuerzas."
    ]
  },
  {
    nombre: "Soledad",
    keywords: ["soledad","solo","abandonado","aislado","me siento solo","sin nadie","solitaria"],
    referencias: [
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Mateo", capitulo: 28, versiculo: 20 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Hebreos", capitulo: 13, versiculo: 5 },
      { libro: "Salmos", capitulo: 27, versiculo: 10 },
      { libro: "Juan", capitulo: 14, versiculo: 18 },
      { libro: "Salmos", capitulo: 102, versiculo: 7 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 142, versiculo: 4 },
      { libro: "Isaías", capitulo: 49, versiculo: 15 },
      { libro: "Salmos", capitulo: 25, versiculo: 16 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 14 },
      { libro: "Salmos", capitulo: 38, versiculo: 11 },
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "Josué", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Lucas", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Apocalipsis", capitulo: 3, versiculo: 20 },
      { libro: "Salmos", capitulo: 33, versiculo: 20 },
      { libro: "Juan", capitulo: 16, versiculo: 32 },
      { libro: "Salmos", capitulo: 39, versiculo: 12 },
      { libro: "Proverbios", capitulo: 18, versiculo: 24 },
      { libro: "Salmos", capitulo: 145, versiculo: 18 },
      { libro: "2 Timoteo", capitulo: 4, versiculo: 17 },
      { libro: "Salmos", capitulo: 73, versiculo: 23 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 91, versiculo: 15 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 }
    ],
    fraseEmpatica: [
      "Dios habita en una casa donde nadie está solo.",
      "Yo estoy contigo todos los días, hasta el fin del mundo.",
      "Aunque mi padre y mi madre me abandonen, el Señor me recogerá.",
      "No te dejaré ni te abandonaré.",
      "Nunca caminas solo; cada paso lo das con un ángel a tu lado."
    ]
  },
  {
    nombre: "Desesperanza / Desánimo",
    keywords: ["desesperanza","desánimo","sin esperanza","rendirse","no puedo más","darse por vencido","desalentado"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 42, versiculo: 5 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 16 },
      { libro: "Salmos", capitulo: 33, versiculo: 22 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 21 },
      { libro: "Salmos", capitulo: 130, versiculo: 5 },
      { libro: "Miqueas", capitulo: 7, versiculo: 7 },
      { libro: "Romanos", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 146, versiculo: 5 },
      { libro: "Jeremías", capitulo: 31, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Habacuc", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 71, versiculo: 14 },
      { libro: "Gálatas", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 119, versiculo: 81 },
      { libro: "Proverbios", capitulo: 24, versiculo: 16 },
      { libro: "Salmos", capitulo: 43, versiculo: 5 },
      { libro: "Isaías", capitulo: 61, versiculo: 3 },
      { libro: "Salmos", capitulo: 9, versiculo: 18 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 33, versiculo: 18 },
      { libro: "2 Tesalonicenses", capitulo: 2, versiculo: 16 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Filipenses", capitulo: 1, versiculo: 6 }
    ],
    fraseEmpatica: [
      "Porque yo sé los planes que tengo para ti, planes de bien.",
      "El Dios de la esperanza os llene de todo gozo y paz.",
      "¿Por qué te abates, alma mía? Espera en Dios.",
      "Aunque el justo caiga siete veces, se levantará.",
      "No te rindas; la cosecha llegará a su tiempo."
    ]
  },
  {
    nombre: "Cansancio / Fatiga",
    keywords: ["cansancio","fatiga","agotado","sin fuerzas","extenuado","rendido"],
    referencias: [
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Isaías", capitulo: 40, versiculo: 29 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Jeremías", capitulo: 31, versiculo: 25 },
      { libro: "Salmos", capitulo: 62, versiculo: 1 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 116, versiculo: 7 },
      { libro: "Éxodo", capitulo: 33, versiculo: 14 },
      { libro: "Salmos", capitulo: 127, versiculo: 2 },
      { libro: "1 Reyes", capitulo: 19, versiculo: 7 },
      { libro: "Salmos", capitulo: 38, versiculo: 9 },
      { libro: "Mateo", capitulo: 6, versiculo: 33 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "2 Corintios", capitulo: 12, versiculo: 9 },
      { libro: "Salmos", capitulo: 68, versiculo: 35 },
      { libro: "Deuteronomio", capitulo: 33, versiculo: 25 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 121, versiculo: 3 },
      { libro: "Proverbios", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 4, versiculo: 8 },
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Colosenses", capitulo: 1, versiculo: 11 },
      { libro: "Salmos", capitulo: 132, versiculo: 14 },
      { libro: "Marcos", capitulo: 6, versiculo: 31 },
      { libro: "Salmos", capitulo: 90, versiculo: 14 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 25, versiculo: 17 },
      { libro: "Romanos", capitulo: 15, versiculo: 32 },
      { libro: "Salmos", capitulo: 34, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Venid a mí los que estáis cansados y agobiados, y yo os haré descansar.",
      "Él da fuerzas al cansado y multiplica el vigor.",
      "En lugares de verdes pastos me hace descansar.",
      "Dios te ofrece un oasis en medio del desierto.",
      "Respira hondo y deja que la paz de Dios llene tu ser."
    ]
  },
  {
    nombre: "Enfermedad / Dolor",
    keywords: ["enfermedad","dolor","enfermo","malestar","padecimiento","sufrimiento físico","hospital","cama"],
    referencias: [
      { libro: "Jeremías", capitulo: 17, versiculo: 14 },
      { libro: "Salmos", capitulo: 41, versiculo: 3 },
      { libro: "Éxodo", capitulo: 15, versiculo: 26 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Isaías", capitulo: 53, versiculo: 5 },
      { libro: "Salmos", capitulo: 30, versiculo: 2 },
      { libro: "Mateo", capitulo: 4, versiculo: 24 },
      { libro: "Salmos", capitulo: 6, versiculo: 2 },
      { libro: "Santiago", capitulo: 5, versiculo: 15 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Jeremías", capitulo: 30, versiculo: 17 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Marcos", capitulo: 5, versiculo: 34 },
      { libro: "Salmos", capitulo: 38, versiculo: 21 },
      { libro: "3 Juan", capitulo: 1, versiculo: 2 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Isaías", capitulo: 57, versiculo: 18 },
      { libro: "Salmos", capitulo: 116, versiculo: 8 },
      { libro: "Mateo", capitulo: 8, versiculo: 17 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "Salmos", capitulo: 34, versiculo: 19 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 15 },
      { libro: "Salmos", capitulo: 91, versiculo: 15 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 56, versiculo: 13 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 71 },
      { libro: "Lucas", capitulo: 8, versiculo: 50 },
      { libro: "Salmos", capitulo: 25, versiculo: 18 },
      { libro: "Romanos", capitulo: 8, versiculo: 18 },
      { libro: "Salmos", capitulo: 9, versiculo: 13 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 24 }
    ],
    fraseEmpatica: [
      "Sáname, Señor, y seré sanado; sálvame, y seré salvo.",
      "Él envió su palabra y los sanó.",
      "Por sus llagas hemos sido sanados.",
      "El Señor te sostendrá en el lecho del dolor.",
      "Dios no te abandona en la enfermedad; está más cerca que nunca."
    ]
  },
  {
    nombre: "Duelo / Pérdida",
    keywords: ["duelo","pérdida","muerte","fallecimiento","difunto","luto","adiós","perder a alguien"],
    referencias: [
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Mateo", capitulo: 5, versiculo: 4 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 4 },
      { libro: "1 Tesalonicenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Isaías", capitulo: 57, versiculo: 15 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Juan", capitulo: 11, versiculo: 25 },
      { libro: "Salmos", capitulo: 116, versiculo: 15 },
      { libro: "Romanos", capitulo: 14, versiculo: 8 },
      { libro: "Salmos", capitulo: 61, versiculo: 2 },
      { libro: "2 Corintios", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 30, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 32 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 55 },
      { libro: "Salmos", capitulo: 48, versiculo: 14 },
      { libro: "Eclesiastés", capitulo: 3, versiculo: 1 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Apocalipsis", capitulo: 14, versiculo: 13 },
      { libro: "Salmos", capitulo: 126, versiculo: 6 },
      { libro: "Hebreos", capitulo: 13, versiculo: 5 },
      { libro: "Salmos", capitulo: 119, versiculo: 50 },
      { libro: "Isaías", capitulo: 66, versiculo: 13 },
      { libro: "Salmos", capitulo: 56, versiculo: 8 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Lucas", capitulo: 7, versiculo: 13 },
      { libro: "Salmos", capitulo: 18, versiculo: 28 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 },
      { libro: "Juan", capitulo: 14, versiculo: 2 },
      { libro: "Salmos", capitulo: 91, versiculo: 11 }
    ],
    fraseEmpatica: [
      "Bienaventurados los que lloran, porque recibirán consolación.",
      "El Señor está cerca de los quebrantados de corazón.",
      "Él enjugará toda lágrima de sus ojos.",
      "Tu ser querido no se ha ido, solo se ha adelantado.",
      "El duelo es la forma más pura de amor. Dios lo entiende."
    ]
  },
  {
    nombre: "Advocaciones marianas / Virgen María",
    keywords: ["maría","virgen","madre","advocación","guadalupe","rosario"],
    referencias: [
      { libro: "Lucas", capitulo: 1, versiculo: 46 },
      { libro: "Juan", capitulo: 19, versiculo: 26 },
      { libro: "Lucas", capitulo: 1, versiculo: 38 },
      { libro: "Hechos", capitulo: 1, versiculo: 14 },
      { libro: "Lucas", capitulo: 2, versiculo: 19 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 1 },
      { libro: "Lucas", capitulo: 1, versiculo: 42 },
      { libro: "Juan", capitulo: 2, versiculo: 5 },
      { libro: "Lucas", capitulo: 1, versiculo: 48 },
      { libro: "Cantar", capitulo: 2, versiculo: 14 },
      { libro: "Lucas", capitulo: 11, versiculo: 27 },
      { libro: "Mateo", capitulo: 12, versiculo: 50 },
      { libro: "Lucas", capitulo: 2, versiculo: 34 },
      { libro: "Juan", capitulo: 19, versiculo: 27 },
      { libro: "Lucas", capitulo: 1, versiculo: 35 },
      { libro: "Génesis", capitulo: 3, versiculo: 15 },
      { libro: "Lucas", capitulo: 1, versiculo: 28 },
      { libro: "Salmos", capitulo: 45, versiculo: 9 },
      { libro: "Lucas", capitulo: 1, versiculo: 45 },
      { libro: "Proverbios", capitulo: 31, versiculo: 10 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 5 },
      { libro: "Eclesiástico", capitulo: 24, versiculo: 1 },
      { libro: "Lucas", capitulo: 2, versiculo: 7 },
      { libro: "Mateo", capitulo: 1, versiculo: 23 },
      { libro: "Lucas", capitulo: 2, versiculo: 51 },
      { libro: "Marcos", capitulo: 3, versiculo: 35 },
      { libro: "Lucas", capitulo: 8, versiculo: 21 },
      { libro: "Apocalipsis", capitulo: 12, versiculo: 17 },
      { libro: "Lucas", capitulo: 1, versiculo: 43 },
      { libro: "Gálatas", capitulo: 4, versiculo: 4 },
      { libro: "Lucas", capitulo: 1, versiculo: 50 },
      { libro: "Sofonías", capitulo: 3, versiculo: 14 },
      { libro: "Lucas", capitulo: 1, versiculo: 47 }
    ],
    fraseEmpatica: [
      "Engrandece mi alma al Señor.",
      "Mujer, he ahí tu hijo.",
      "He aquí la sierva del Señor.",
      "Santa María, Madre de Dios, ruega por nosotros.",
      "Acude a María, ella te guiará a Jesús."
    ]
  },
  {
    nombre: "Paz interior",
    keywords: ["paz interior","calma","serenidad","tranquilidad","paz mental","sosiego"],
    referencias: [
      { libro: "Juan", capitulo: 14, versiculo: 27 },
      { libro: "Filipenses", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Isaías", capitulo: 26, versiculo: 3 },
      { libro: "Salmos", capitulo: 4, versiculo: 8 },
      { libro: "Números", capitulo: 6, versiculo: 26 },
      { libro: "Salmos", capitulo: 119, versiculo: 165 },
      { libro: "Isaías", capitulo: 32, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 11 },
      { libro: "Mateo", capitulo: 5, versiculo: 9 },
      { libro: "Salmos", capitulo: 34, versiculo: 14 },
      { libro: "Romanos", capitulo: 14, versiculo: 17 },
      { libro: "Salmos", capitulo: 72, versiculo: 7 },
      { libro: "Colosenses", capitulo: 3, versiculo: 15 },
      { libro: "Salmos", capitulo: 122, versiculo: 6 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 16 },
      { libro: "Salmos", capitulo: 85, versiculo: 8 },
      { libro: "Gálatas", capitulo: 5, versiculo: 22 },
      { libro: "Salmos", capitulo: 46, versiculo: 10 },
      { libro: "Juan", capitulo: 16, versiculo: 33 },
      { libro: "Salmos", capitulo: 131, versiculo: 2 },
      { libro: "Proverbios", capitulo: 12, versiculo: 20 },
      { libro: "Salmos", capitulo: 37, versiculo: 37 },
      { libro: "Efesios", capitulo: 2, versiculo: 14 },
      { libro: "Salmos", capitulo: 55, versiculo: 18 },
      { libro: "Isaías", capitulo: 55, versiculo: 12 },
      { libro: "Salmos", capitulo: 23, versiculo: 2 },
      { libro: "Mateo", capitulo: 11, versiculo: 29 },
      { libro: "Salmos", capitulo: 62, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 119, versiculo: 76 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 147, versiculo: 14 }
    ],
    fraseEmpatica: [
      "La paz os dejo, mi paz os doy; no se turbe vuestro corazón.",
      "La paz de Dios guardará vuestros corazones.",
      "El Señor bendice a su pueblo con paz.",
      "Quédate quieto, reconoce que Él es Dios.",
      "Respira. Dios está en el centro de tu ser."
    ]
  },
  {
    nombre: "Fortaleza / Valentía",
    keywords: ["fortaleza","valentía","fuerza","coraje","ánimo","valiente","no puedo más"],
    referencias: [
      { libro: "Josué", capitulo: 1, versiculo: 9 },
      { libro: "Isaías", capitulo: 41, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "2 Timoteo", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 18, versiculo: 32 },
      { libro: "Efesios", capitulo: 6, versiculo: 10 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 138, versiculo: 3 },
      { libro: "1 Corintios", capitulo: 16, versiculo: 13 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Isaías", capitulo: 40, versiculo: 29 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Romanos", capitulo: 8, versiculo: 31 },
      { libro: "Salmos", capitulo: 84, versiculo: 5 },
      { libro: "Habacuc", capitulo: 3, versiculo: 19 },
      { libro: "Salmos", capitulo: 68, versiculo: 35 },
      { libro: "Isaías", capitulo: 12, versiculo: 2 },
      { libro: "Salmos", capitulo: 121, versiculo: 2 },
      { libro: "1 Juan", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 144, versiculo: 1 },
      { libro: "Proverbios", capitulo: 24, versiculo: 10 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 },
      { libro: "Éxodo", capitulo: 15, versiculo: 2 },
      { libro: "Salmos", capitulo: 56, versiculo: 4 },
      { libro: "Lucas", capitulo: 1, versiculo: 37 },
      { libro: "Salmos", capitulo: 44, versiculo: 5 },
      { libro: "Nehemías", capitulo: 8, versiculo: 10 },
      { libro: "Salmos", capitulo: 18, versiculo: 39 },
      { libro: "Mateo", capitulo: 19, versiculo: 26 },
      { libro: "Salmos", capitulo: 60, versiculo: 12 }
    ],
    fraseEmpatica: [
      "Esfuérzate y sé valiente; no temas ni desmayes.",
      "El Señor es mi luz y mi salvación.",
      "Todo lo puedo en Cristo que me fortalece.",
      "Dios es nuestro refugio y fortaleza.",
      "Levántate. La fuerza que necesitas ya ha sido puesta en ti."
    ]
  },
  {
    nombre: "Protección / Refugio",
    keywords: ["protección","refugio","seguro","escudo","amparo","defensa","peligro"],
    referencias: [
      { libro: "Salmos", capitulo: 91, versiculo: 2 },
      { libro: "Proverbios", capitulo: 18, versiculo: 10 },
      { libro: "Salmos", capitulo: 46, versiculo: 1 },
      { libro: "Salmos", capitulo: 121, versiculo: 7 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 3 },
      { libro: "Salmos", capitulo: 32, versiculo: 7 },
      { libro: "Isaías", capitulo: 54, versiculo: 17 },
      { libro: "Salmos", capitulo: 27, versiculo: 5 },
      { libro: "Nahúm", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 34, versiculo: 7 },
      { libro: "Deuteronomio", capitulo: 31, versiculo: 6 },
      { libro: "Salmos", capitulo: 125, versiculo: 2 },
      { libro: "Salmos", capitulo: 140, versiculo: 4 },
      { libro: "Juan", capitulo: 17, versiculo: 15 },
      { libro: "Salmos", capitulo: 61, versiculo: 4 },
      { libro: "1 Pedro", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 138, versiculo: 7 },
      { libro: "Mateo", capitulo: 6, versiculo: 13 },
      { libro: "Salmos", capitulo: 41, versiculo: 2 },
      { libro: "Efesios", capitulo: 6, versiculo: 11 },
      { libro: "Salmos", capitulo: 91, versiculo: 11 },
      { libro: "2 Samuel", capitulo: 22, versiculo: 3 },
      { libro: "Salmos", capitulo: 16, versiculo: 1 },
      { libro: "Isaías", capitulo: 43, versiculo: 2 },
      { libro: "Salmos", capitulo: 18, versiculo: 2 },
      { libro: "Proverbios", capitulo: 30, versiculo: 5 },
      { libro: "Salmos", capitulo: 144, versiculo: 2 },
      { libro: "Lucas", capitulo: 10, versiculo: 19 },
      { libro: "Salmos", capitulo: 23, versiculo: 4 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "Salmos", capitulo: 55, versiculo: 16 },
      { libro: "Jeremías", capitulo: 15, versiculo: 21 },
      { libro: "Salmos", capitulo: 145, versiculo: 20 }
    ],
    fraseEmpatica: [
      "El que habita al amparo del Altísimo descansará.",
      "Torre fuerte es el nombre del Señor.",
      "Dios es nuestro amparo y fortaleza.",
      "Bajo sus alas encuentras el refugio más seguro.",
      "Muros invisibles te rodean; el cielo entero vela por ti."
    ]
  },
  {
    nombre: "Fe / Confianza en Dios",
    keywords: ["fe","confianza","creer","duda","confiar","credulidad"],
    referencias: [
      { libro: "Hebreos", capitulo: 11, versiculo: 1 },
      { libro: "Proverbios", capitulo: 3, versiculo: 5 },
      { libro: "Salmos", capitulo: 37, versiculo: 5 },
      { libro: "Marcos", capitulo: 11, versiculo: 22 },
      { libro: "Salmos", capitulo: 56, versiculo: 3 },
      { libro: "Mateo", capitulo: 17, versiculo: 20 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Isaías", capitulo: 26, versiculo: 4 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Romanos", capitulo: 10, versiculo: 17 },
      { libro: "Salmos", capitulo: 9, versiculo: 10 },
      { libro: "2 Corintios", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 40, versiculo: 4 },
      { libro: "Juan", capitulo: 20, versiculo: 29 },
      { libro: "Salmos", capitulo: 118, versiculo: 8 },
      { libro: "Santiago", capitulo: 1, versiculo: 6 },
      { libro: "Salmos", capitulo: 25, versiculo: 2 },
      { libro: "1 Juan", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 32, versiculo: 10 },
      { libro: "Mateo", capitulo: 21, versiculo: 22 },
      { libro: "Salmos", capitulo: 115, versiculo: 11 },
      { libro: "Gálatas", capitulo: 2, versiculo: 20 },
      { libro: "Salmos", capitulo: 31, versiculo: 14 },
      { libro: "Efesios", capitulo: 2, versiculo: 8 },
      { libro: "Salmos", capitulo: 121, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 19 },
      { libro: "Salmos", capitulo: 112, versiculo: 7 },
      { libro: "Lucas", capitulo: 1, versiculo: 37 },
      { libro: "Salmos", capitulo: 146, versiculo: 3 },
      { libro: "Romanos", capitulo: 8, versiculo: 28 },
      { libro: "Salmos", capitulo: 34, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 84, versiculo: 12 }
    ],
    fraseEmpatica: [
      "La fe es la certeza de lo que se espera.",
      "Confía en el Señor con todo tu corazón.",
      "Encomienda al Señor tu camino.",
      "Tened fe en Dios.",
      "No necesitas entender el plan; solo confiar en el Arquitecto."
    ]
  },
  {
    nombre: "Oración / Vida espiritual",
    keywords: ["oración","rezar","vida espiritual","comunión","hablar con Dios","espiritualidad","meditación"],
    referencias: [
      { libro: "Mateo", capitulo: 6, versiculo: 6 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 17 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 145, versiculo: 18 },
      { libro: "Jeremías", capitulo: 33, versiculo: 3 },
      { libro: "Salmos", capitulo: 55, versiculo: 17 },
      { libro: "Lucas", capitulo: 18, versiculo: 1 },
      { libro: "Salmos", capitulo: 5, versiculo: 3 },
      { libro: "Romanos", capitulo: 12, versiculo: 12 },
      { libro: "Salmos", capitulo: 141, versiculo: 2 },
      { libro: "Marcos", capitulo: 1, versiculo: 35 },
      { libro: "Salmos", capitulo: 88, versiculo: 13 },
      { libro: "Santiago", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 102, versiculo: 1 },
      { libro: "Efesios", capitulo: 6, versiculo: 18 },
      { libro: "Salmos", capitulo: 17, versiculo: 1 },
      { libro: "Mateo", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 109, versiculo: 4 },
      { libro: "Hechos", capitulo: 1, versiculo: 14 },
      { libro: "Salmos", capitulo: 65, versiculo: 2 },
      { libro: "1 Juan", capitulo: 5, versiculo: 14 },
      { libro: "Salmos", capitulo: 28, versiculo: 6 },
      { libro: "Daniel", capitulo: 6, versiculo: 10 },
      { libro: "Salmos", capitulo: 119, versiculo: 147 },
      { libro: "Mateo", capitulo: 26, versiculo: 41 },
      { libro: "Salmos", capitulo: 54, versiculo: 2 },
      { libro: "Colosenses", capitulo: 4, versiculo: 2 },
      { libro: "Salmos", capitulo: 145, versiculo: 1 },
      { libro: "Lucas", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 19, versiculo: 14 },
      { libro: "Salmos", capitulo: 34, versiculo: 15 },
      { libro: "Isaías", capitulo: 65, versiculo: 24 },
      { libro: "Salmos", capitulo: 143, versiculo: 1 }
    ],
    fraseEmpatica: [
      "Entra en tu aposento y ora a tu Padre en secreto.",
      "Orad sin cesar.",
      "Cercano está el Señor a los que le invocan.",
      "Cuando no sepas qué decir, di: 'Aquí estoy, Señor'.",
      "Habla con Dios como con un amigo; Él te escucha."
    ]
  },
  {
    nombre: "Salud física y espiritual",
    keywords: ["salud","bienestar","sano","cuidado","cuerpo","mente sana"],
    referencias: [
      { libro: "3 Juan", capitulo: 1, versiculo: 2 },
      { libro: "1 Corintios", capitulo: 6, versiculo: 19 },
      { libro: "Éxodo", capitulo: 15, versiculo: 26 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Proverbios", capitulo: 4, versiculo: 20 },
      { libro: "Isaías", capitulo: 58, versiculo: 8 },
      { libro: "Salmos", capitulo: 38, versiculo: 3 },
      { libro: "Jeremías", capitulo: 33, versiculo: 6 },
      { libro: "Salmos", capitulo: 41, versiculo: 3 },
      { libro: "1 Timoteo", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 30, versiculo: 2 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 15 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Marcos", capitulo: 5, versiculo: 34 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Lucas", capitulo: 9, versiculo: 11 },
      { libro: "Salmos", capitulo: 73, versiculo: 26 },
      { libro: "Romanos", capitulo: 12, versiculo: 1 },
      { libro: "Salmos", capitulo: 6, versiculo: 2 },
      { libro: "Proverbios", capitulo: 14, versiculo: 30 },
      { libro: "Salmos", capitulo: 119, versiculo: 73 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 139, versiculo: 14 },
      { libro: "Mateo", capitulo: 4, versiculo: 23 },
      { libro: "Salmos", capitulo: 34, versiculo: 19 },
      { libro: "Santiago", capitulo: 5, versiculo: 15 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 },
      { libro: "Filipenses", capitulo: 4, versiculo: 13 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Apocalipsis", capitulo: 22, versiculo: 2 },
      { libro: "Salmos", capitulo: 91, versiculo: 16 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 24 },
      { libro: "Salmos", capitulo: 37, versiculo: 3 }
    ],
    fraseEmpatica: [
      "Amado, ruego que tengas salud en todas las cosas.",
      "Vuestro cuerpo es templo del Espíritu Santo.",
      "Él sana a los quebrantados de corazón.",
      "Cuida tu cuerpo, sagrario donde habita Dios.",
      "La verdadera salud es estar en armonía con tu Creador."
    ]
  },
  {
    nombre: "Sanación interior / Liberación",
    keywords: ["sanación interior","liberación","curación","heridas","pasado","trauma"],
    referencias: [
      { libro: "Isaías", capitulo: 61, versiculo: 1 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "Joel", capitulo: 2, versiculo: 25 },
      { libro: "Lucas", capitulo: 4, versiculo: 18 },
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Jeremías", capitulo: 30, versiculo: 17 },
      { libro: "Salmos", capitulo: 103, versiculo: 4 },
      { libro: "2 Corintios", capitulo: 5, versiculo: 17 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "Ezequiel", capitulo: 36, versiculo: 26 },
      { libro: "Salmos", capitulo: 40, versiculo: 2 },
      { libro: "Mateo", capitulo: 11, versiculo: 28 },
      { libro: "Salmos", capitulo: 107, versiculo: 20 },
      { libro: "Romanos", capitulo: 8, versiculo: 1 },
      { libro: "Salmos", capitulo: 32, versiculo: 5 },
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Isaías", capitulo: 43, versiculo: 18 },
      { libro: "Salmos", capitulo: 126, versiculo: 1 },
      { libro: "Juan", capitulo: 8, versiculo: 36 },
      { libro: "Salmos", capitulo: 25, versiculo: 7 },
      { libro: "Gálatas", capitulo: 5, versiculo: 1 },
      { libro: "Salmos", capitulo: 71, versiculo: 20 },
      { libro: "Filipenses", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 119, versiculo: 133 },
      { libro: "Colosenses", capitulo: 1, versiculo: 13 },
      { libro: "Salmos", capitulo: 18, versiculo: 19 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 5 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Hebreos", capitulo: 12, versiculo: 1 },
      { libro: "Salmos", capitulo: 55, versiculo: 18 },
      { libro: "Isaías", capitulo: 53, versiculo: 5 },
      { libro: "Salmos", capitulo: 30, versiculo: 11 }
    ],
    fraseEmpatica: [
      "El Espíritu del Señor está sobre mí… para sanar.",
      "Él restaura lo que el tiempo se llevó.",
      "Os restauraré los años que comió la oruga.",
      "Tus cicatrices no te definen; son trofeos de batallas superadas.",
      "Eres libre, aunque aún no lo sientas. Camina en esa verdad."
    ]
  },
  {
    nombre: "Arrepentimiento / Confesión",
    keywords: ["arrepentimiento","confesión","culpa","perdón","pecado","remordimiento"],
    referencias: [
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 51, versiculo: 1 },
      { libro: "Proverbios", capitulo: 28, versiculo: 13 },
      { libro: "Salmos", capitulo: 32, versiculo: 5 },
      { libro: "Hechos", capitulo: 3, versiculo: 19 },
      { libro: "Salmos", capitulo: 38, versiculo: 18 },
      { libro: "Isaías", capitulo: 1, versiculo: 18 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Lucas", capitulo: 15, versiculo: 21 },
      { libro: "Salmos", capitulo: 25, versiculo: 11 },
      { libro: "Ezequiel", capitulo: 18, versiculo: 21 },
      { libro: "Salmos", capitulo: 130, versiculo: 4 },
      { libro: "Mateo", capitulo: 3, versiculo: 2 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Hechos", capitulo: 2, versiculo: 38 },
      { libro: "Salmos", capitulo: 34, versiculo: 18 },
      { libro: "Daniel", capitulo: 9, versiculo: 9 },
      { libro: "Salmos", capitulo: 86, versiculo: 5 },
      { libro: "Romanos", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 59 },
      { libro: "Lucas", capitulo: 18, versiculo: 13 },
      { libro: "Salmos", capitulo: 19, versiculo: 12 },
      { libro: "Marcos", capitulo: 1, versiculo: 15 },
      { libro: "Salmos", capitulo: 147, versiculo: 3 },
      { libro: "2 Crónicas", capitulo: 7, versiculo: 14 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "1 Juan", capitulo: 2, versiculo: 1 },
      { libro: "Salmos", capitulo: 79, versiculo: 9 },
      { libro: "Proverbios", capitulo: 28, versiculo: 13 },
      { libro: "Salmos", capitulo: 41, versiculo: 4 },
      { libro: "Jonás", capitulo: 3, versiculo: 10 },
      { libro: "Salmos", capitulo: 69, versiculo: 5 },
      { libro: "Santiago", capitulo: 5, versiculo: 16 }
    ],
    fraseEmpatica: [
      "Si confesamos nuestros pecados, Él es fiel para perdonar.",
      "Ten piedad de mí, oh Dios, conforme a tu gran amor.",
      "Aunque vuestros pecados sean como la grana, serán emblanquecidos.",
      "No temas acercarte a Dios con tu culpa.",
      "El arrepentimiento es la puerta hacia la libertad."
    ]
  },
  {
    nombre: "Perdón",
    keywords: ["perdón","perdonar","rencor","resentimiento","ofensa","reconciliación"],
    referencias: [
      { libro: "Mateo", capitulo: 6, versiculo: 14 },
      { libro: "Efesios", capitulo: 4, versiculo: 32 },
      { libro: "Colosenses", capitulo: 3, versiculo: 13 },
      { libro: "Mateo", capitulo: 18, versiculo: 21 },
      { libro: "Lucas", capitulo: 6, versiculo: 37 },
      { libro: "Salmos", capitulo: 103, versiculo: 12 },
      { libro: "Isaías", capitulo: 43, versiculo: 25 },
      { libro: "Mateo", capitulo: 5, versiculo: 23 },
      { libro: "Marcos", capitulo: 11, versiculo: 25 },
      { libro: "1 Juan", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 32, versiculo: 1 },
      { libro: "Romanos", capitulo: 12, versiculo: 19 },
      { libro: "Salmos", capitulo: 130, versiculo: 4 },
      { libro: "Lucas", capitulo: 23, versiculo: 34 },
      { libro: "Salmos", capitulo: 79, versiculo: 9 },
      { libro: "Proverbios", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 86, versiculo: 5 },
      { libro: "Hechos", capitulo: 7, versiculo: 60 },
      { libro: "Salmos", capitulo: 25, versiculo: 18 },
      { libro: "Mateo", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 51, versiculo: 9 },
      { libro: "2 Corintios", capitulo: 2, versiculo: 7 },
      { libro: "Salmos", capitulo: 65, versiculo: 3 },
      { libro: "Génesis", capitulo: 50, versiculo: 17 },
      { libro: "Salmos", capitulo: 99, versiculo: 8 },
      { libro: "Lucas", capitulo: 17, versiculo: 4 },
      { libro: "Salmos", capitulo: 103, versiculo: 3 },
      { libro: "Efesios", capitulo: 1, versiculo: 7 },
      { libro: "Salmos", capitulo: 34, versiculo: 22 },
      { libro: "1 Pedro", capitulo: 4, versiculo: 8 },
      { libro: "Salmos", capitulo: 85, versiculo: 2 },
      { libro: "Colosenses", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 107, versiculo: 17 }
    ],
    fraseEmpatica: [
      "Si perdonáis a otros, vuestro Padre os perdonará.",
      "Sed bondadosos y compasivos, perdonándoos mutuamente.",
      "No te digo hasta siete veces, sino hasta setenta veces siete.",
      "El perdón no justifica al ofensor, te libera a ti.",
      "Padre, perdónalos, porque no saben lo que hacen."
    ]
  },
  {
    nombre: "Tentación / Pecado",
    keywords: ["tentación","pecado","caer","error","vicio","lucha"],
    referencias: [
      { libro: "1 Corintios", capitulo: 10, versiculo: 13 },
      { libro: "Mateo", capitulo: 26, versiculo: 41 },
      { libro: "Santiago", capitulo: 1, versiculo: 12 },
      { libro: "Salmos", capitulo: 119, versiculo: 11 },
      { libro: "Hebreos", capitulo: 2, versiculo: 18 },
      { libro: "Salmos", capitulo: 19, versiculo: 13 },
      { libro: "Gálatas", capitulo: 6, versiculo: 1 },
      { libro: "Salmos", capitulo: 39, versiculo: 1 },
      { libro: "2 Pedro", capitulo: 2, versiculo: 9 },
      { libro: "Salmos", capitulo: 51, versiculo: 10 },
      { libro: "Romanos", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 141, versiculo: 4 },
      { libro: "Lucas", capitulo: 22, versiculo: 40 },
      { libro: "Salmos", capitulo: 17, versiculo: 4 },
      { libro: "Efesios", capitulo: 6, versiculo: 13 },
      { libro: "Salmos", capitulo: 119, versiculo: 9 },
      { libro: "1 Juan", capitulo: 2, versiculo: 16 },
      { libro: "Salmos", capitulo: 38, versiculo: 1 },
      { libro: "Mateo", capitulo: 4, versiculo: 10 },
      { libro: "Salmos", capitulo: 130, versiculo: 3 },
      { libro: "Proverbios", capitulo: 4, versiculo: 23 },
      { libro: "Salmos", capitulo: 25, versiculo: 15 },
      { libro: "Romanos", capitulo: 7, versiculo: 24 },
      { libro: "Salmos", capitulo: 119, versiculo: 133 },
      { libro: "Tito", capitulo: 2, versiculo: 12 },
      { libro: "Salmos", capitulo: 44, versiculo: 21 },
      { libro: "Hebreos", capitulo: 4, versiculo: 15 },
      { libro: "Salmos", capitulo: 139, versiculo: 23 },
      { libro: "Santiago", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 90, versiculo: 8 },
      { libro: "1 Timoteo", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 18, versiculo: 23 },
      { libro: "Apocalipsis", capitulo: 3, versiculo: 10 }
    ],
    fraseEmpatica: [
      "No os ha sobrevenido ninguna tentación que no sea humana.",
      "Velad y orad para que no entréis en tentación.",
      "Resistid al diablo y huirá de vosotros.",
      "La tentación no es pecado; lo es ceder a ella.",
      "Eres más fuerte de lo que crees; el que está en ti es mayor."
    ]
  },
  {
    nombre: "Familia / Hogar",
    keywords: ["familia","hogar","hijo","padres","esposo","matrimonio","casa"],
    referencias: [
      { libro: "Josué", capitulo: 24, versiculo: 15 },
      { libro: "Salmos", capitulo: 127, versiculo: 1 },
      { libro: "Proverbios", capitulo: 22, versiculo: 6 },
      { libro: "Efesios", capitulo: 6, versiculo: 1 },
      { libro: "Salmos", capitulo: 128, versiculo: 3 },
      { libro: "Colosenses", capitulo: 3, versiculo: 20 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "1 Timoteo", capitulo: 5, versiculo: 8 },
      { libro: "Salmos", capitulo: 103, versiculo: 17 },
      { libro: "Mateo", capitulo: 19, versiculo: 5 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Génesis", capitulo: 2, versiculo: 24 },
      { libro: "Salmos", capitulo: 127, versiculo: 3 },
      { libro: "Proverbios", capitulo: 1, versiculo: 8 },
      { libro: "Salmos", capitulo: 112, versiculo: 2 },
      { libro: "Deuteronomio", capitulo: 6, versiculo: 7 },
      { libro: "Salmos", capitulo: 78, versiculo: 6 },
      { libro: "Efesios", capitulo: 5, versiculo: 25 },
      { libro: "Salmos", capitulo: 144, versiculo: 12 },
      { libro: "Isaías", capitulo: 54, versiculo: 13 },
      { libro: "Salmos", capitulo: 34, versiculo: 11 },
      { libro: "Tito", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 128, versiculo: 6 },
      { libro: "Hebreos", capitulo: 13, versiculo: 4 },
      { libro: "Salmos", capitulo: 115, versiculo: 14 },
      { libro: "Lucas", capitulo: 15, versiculo: 20 },
      { libro: "Salmos", capitulo: 145, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 3, versiculo: 7 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Proverbios", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 91, versiculo: 9 },
      { libro: "Malaquías", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 }
    ],
    fraseEmpatica: [
      "Yo y mi casa serviremos al Señor.",
      "Si el Señor no edifica la casa, en vano trabajan.",
      "Instruye al niño en su camino.",
      "La familia es el primer templo donde aprendemos a amar.",
      "Bendice, Señor, nuestro hogar y hazlo reflejo de tu amor."
    ]
  },
  {
    nombre: "Amor de Dios",
    keywords: ["amor de Dios","amor divino","Dios me ama","amor eterno"],
    referencias: [
      { libro: "Juan", capitulo: 3, versiculo: 16 },
      { libro: "Romanos", capitulo: 8, versiculo: 38 },
      { libro: "1 Juan", capitulo: 4, versiculo: 9 },
      { libro: "Jeremías", capitulo: 31, versiculo: 3 },
      { libro: "Salmos", capitulo: 136, versiculo: 26 },
      { libro: "Efesios", capitulo: 2, versiculo: 4 },
      { libro: "1 Juan", capitulo: 4, versiculo: 16 },
      { libro: "Salmos", capitulo: 103, versiculo: 8 },
      { libro: "Romanos", capitulo: 5, versiculo: 8 },
      { libro: "Sofonías", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 86, versiculo: 15 },
      { libro: "1 Juan", capitulo: 3, versiculo: 1 },
      { libro: "Salmos", capitulo: 63, versiculo: 3 },
      { libro: "Juan", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 36, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 35 },
      { libro: "Salmos", capitulo: 103, versiculo: 11 },
      { libro: "Isaías", capitulo: 54, versiculo: 10 },
      { libro: "Salmos", capitulo: 52, versiculo: 8 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 22 },
      { libro: "Salmos", capitulo: 59, versiculo: 16 },
      { libro: "Deuteronomio", capitulo: 7, versiculo: 9 },
      { libro: "Salmos", capitulo: 23, versiculo: 6 },
      { libro: "1 Corintios", capitulo: 13, versiculo: 7 },
      { libro: "Salmos", capitulo: 143, versiculo: 8 },
      { libro: "Juan", capitulo: 17, versiculo: 26 },
      { libro: "Salmos", capitulo: 139, versiculo: 17 },
      { libro: "Apocalipsis", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 109, versiculo: 21 },
      { libro: "Oseas", capitulo: 11, versiculo: 4 },
      { libro: "Salmos", capitulo: 32, versiculo: 10 },
      { libro: "1 Juan", capitulo: 4, versiculo: 10 },
      { libro: "Salmos", capitulo: 145, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Porque de tal manera amó Dios al mundo.",
      "Ni la muerte ni la vida podrán separarnos del amor de Dios.",
      "Con amor eterno te he amado.",
      "Dios es amor.",
      "Eres amado sin condiciones, sin límites."
    ]
  },
  {
    nombre: "Amor al prójimo",
    keywords: ["amor al prójimo","caridad","ayudar","servicio","compartir"],
    referencias: [
      { libro: "Mateo", capitulo: 22, versiculo: 39 },
      { libro: "Juan", capitulo: 13, versiculo: 34 },
      { libro: "1 Juan", capitulo: 4, versiculo: 20 },
      { libro: "Lucas", capitulo: 6, versiculo: 31 },
      { libro: "Romanos", capitulo: 13, versiculo: 10 },
      { libro: "1 Corintios", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 41, versiculo: 1 },
      { libro: "Proverbios", capitulo: 19, versiculo: 17 },
      { libro: "Mateo", capitulo: 25, versiculo: 40 },
      { libro: "Gálatas", capitulo: 6, versiculo: 2 },
      { libro: "Salmos", capitulo: 112, versiculo: 9 },
      { libro: "Hebreos", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 82, versiculo: 3 },
      { libro: "Santiago", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 21 },
      { libro: "Lucas", capitulo: 10, versiculo: 30 },
      { libro: "Salmos", capitulo: 146, versiculo: 9 },
      { libro: "1 Juan", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 140, versiculo: 12 },
      { libro: "Mateo", capitulo: 5, versiculo: 42 },
      { libro: "Salmos", capitulo: 72, versiculo: 12 },
      { libro: "Deuteronomio", capitulo: 15, versiculo: 11 },
      { libro: "Salmos", capitulo: 34, versiculo: 14 },
      { libro: "Lucas", capitulo: 14, versiculo: 13 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "Filipenses", capitulo: 2, versiculo: 4 },
      { libro: "Salmos", capitulo: 10, versiculo: 17 },
      { libro: "1 Pedro", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 112, versiculo: 5 },
      { libro: "Proverbios", capitulo: 21, versiculo: 13 },
      { libro: "Salmos", capitulo: 15, versiculo: 3 },
      { libro: "Romanos", capitulo: 12, versiculo: 15 },
      { libro: "Salmos", capitulo: 29, versiculo: 11 }
    ],
    fraseEmpatica: [
      "Amarás a tu prójimo como a ti mismo.",
      "Un mandamiento nuevo os doy: que os améis unos a otros.",
      "Todo lo que hicisteis por uno de mis hermanos, por mí lo hicisteis.",
      "El amor es paciente, es bondadoso.",
      "En el rostro del necesitado, Cristo te mira."
    ]
  },
  {
    nombre: "Amistad",
    keywords: ["amistad","amigo","compañero","confidente","lealtad"],
    referencias: [
      { libro: "Proverbios", capitulo: 17, versiculo: 17 },
      { libro: "Juan", capitulo: 15, versiculo: 13 },
      { libro: "Proverbios", capitulo: 18, versiculo: 24 },
      { libro: "Eclesiastés", capitulo: 4, versiculo: 9 },
      { libro: "Salmos", capitulo: 133, versiculo: 1 },
      { libro: "Proverbios", capitulo: 27, versiculo: 6 },
      { libro: "Job", capitulo: 6, versiculo: 14 },
      { libro: "Salmos", capitulo: 35, versiculo: 14 },
      { libro: "Proverbios", capitulo: 27, versiculo: 9 },
      { libro: "1 Samuel", capitulo: 18, versiculo: 1 },
      { libro: "Salmos", capitulo: 88, versiculo: 18 },
      { libro: "Proverbios", capitulo: 27, versiculo: 17 },
      { libro: "Lucas", capitulo: 11, versiculo: 5 },
      { libro: "Salmos", capitulo: 55, versiculo: 13 },
      { libro: "Job", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 41, versiculo: 9 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 33 },
      { libro: "Salmos", capitulo: 119, versiculo: 63 },
      { libro: "Santiago", capitulo: 2, versiculo: 23 },
      { libro: "Salmos", capitulo: 31, versiculo: 11 },
      { libro: "Proverbios", capitulo: 22, versiculo: 24 },
      { libro: "Salmos", capitulo: 38, versiculo: 11 },
      { libro: "Eclesiástico", capitulo: 6, versiculo: 14 },
      { libro: "Salmos", capitulo: 109, versiculo: 4 },
      { libro: "Juan", capitulo: 11, versiculo: 35 },
      { libro: "Salmos", capitulo: 142, versiculo: 4 },
      { libro: "Proverbios", capitulo: 17, versiculo: 9 },
      { libro: "Salmos", capitulo: 25, versiculo: 14 },
      { libro: "Romanos", capitulo: 12, versiculo: 10 },
      { libro: "Salmos", capitulo: 27, versiculo: 9 },
      { libro: "Colosenses", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 11 }
    ],
    fraseEmpatica: [
      "En todo tiempo ama el amigo.",
      "Nadie tiene mayor amor que este.",
      "Hay amigos más fieles que un hermano.",
      "Un amigo fiel es un refugio seguro.",
      "Donde hay un amigo, hay un pedacito de cielo."
    ]
  },
  {
    nombre: "Gratitud / Acción de gracias",
    keywords: ["gratitud","gracias","agradecimiento","bendición","dar gracias"],
    referencias: [
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 18 },
      { libro: "Salmos", capitulo: 100, versiculo: 4 },
      { libro: "Colosenses", capitulo: 3, versiculo: 15 },
      { libro: "Salmos", capitulo: 136, versiculo: 1 },
      { libro: "Filipenses", capitulo: 4, versiculo: 6 },
      { libro: "Salmos", capitulo: 118, versiculo: 1 },
      { libro: "Efesios", capitulo: 5, versiculo: 20 },
      { libro: "Salmos", capitulo: 107, versiculo: 1 },
      { libro: "Lucas", capitulo: 17, versiculo: 16 },
      { libro: "Salmos", capitulo: 95, versiculo: 2 },
      { libro: "2 Corintios", capitulo: 9, versiculo: 15 },
      { libro: "Salmos", capitulo: 50, versiculo: 14 },
      { libro: "Daniel", capitulo: 2, versiculo: 23 },
      { libro: "Salmos", capitulo: 103, versiculo: 2 },
      { libro: "Juan", capitulo: 6, versiculo: 11 },
      { libro: "Salmos", capitulo: 75, versiculo: 1 },
      { libro: "Apocalipsis", capitulo: 11, versiculo: 17 },
      { libro: "Salmos", capitulo: 116, versiculo: 12 },
      { libro: "Hechos", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 28, versiculo: 7 },
      { libro: "Romanos", capitulo: 1, versiculo: 21 },
      { libro: "Salmos", capitulo: 34, versiculo: 1 },
      { libro: "1 Crónicas", capitulo: 16, versiculo: 34 },
      { libro: "Salmos", capitulo: 138, versiculo: 1 },
      { libro: "Colosenses", capitulo: 2, versiculo: 7 },
      { libro: "Salmos", capitulo: 30, versiculo: 12 },
      { libro: "Lucas", capitulo: 22, versiculo: 19 },
      { libro: "Salmos", capitulo: 7, versiculo: 17 },
      { libro: "Isaías", capitulo: 12, versiculo: 4 },
      { libro: "Salmos", capitulo: 69, versiculo: 30 },
      { libro: "Hebreos", capitulo: 12, versiculo: 28 },
      { libro: "Salmos", capitulo: 145, versiculo: 10 },
      { libro: "Jonás", capitulo: 2, versiculo: 9 }
    ],
    fraseEmpatica: [
      "Dad gracias en todo.",
      "Entrad por sus puertas con acción de gracias.",
      "Sed agradecidos.",
      "Bendice, alma mía, al Señor.",
      "La gratitud es la memoria del corazón."
    ]
  },
  {
    nombre: "Alegría / Gozo",
    keywords: ["alegría","gozo","felicidad","contento","júbilo","regocijo"],
    referencias: [
      { libro: "Salmos", capitulo: 118, versiculo: 24 },
      { libro: "Filipenses", capitulo: 4, versiculo: 4 },
      { libro: "Salmos", capitulo: 16, versiculo: 11 },
      { libro: "Nehemías", capitulo: 8, versiculo: 10 },
      { libro: "Salmos", capitulo: 30, versiculo: 11 },
      { libro: "Proverbios", capitulo: 17, versiculo: 22 },
      { libro: "Salmos", capitulo: 126, versiculo: 2 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 32, versiculo: 11 },
      { libro: "Gálatas", capitulo: 5, versiculo: 22 },
      { libro: "Salmos", capitulo: 5, versiculo: 11 },
      { libro: "Lucas", capitulo: 10, versiculo: 21 },
      { libro: "Salmos", capitulo: 33, versiculo: 1 },
      { libro: "1 Tesalonicenses", capitulo: 5, versiculo: 16 },
      { libro: "Salmos", capitulo: 97, versiculo: 12 },
      { libro: "Isaías", capitulo: 35, versiculo: 10 },
      { libro: "Salmos", capitulo: 149, versiculo: 2 },
      { libro: "Juan", capitulo: 15, versiculo: 11 },
      { libro: "Salmos", capitulo: 68, versiculo: 3 },
      { libro: "Proverbios", capitulo: 10, versiculo: 28 },
      { libro: "Salmos", capitulo: 94, versiculo: 19 },
      { libro: "Habacuc", capitulo: 3, versiculo: 18 },
      { libro: "Salmos", capitulo: 4, versiculo: 7 },
      { libro: "Hechos", capitulo: 16, versiculo: 34 },
      { libro: "Salmos", capitulo: 126, versiculo: 5 },
      { libro: "Mateo", capitulo: 2, versiculo: 10 },
      { libro: "Salmos", capitulo: 64, versiculo: 10 },
      { libro: "Sofonías", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 90, versiculo: 14 },
      { libro: "Filipenses", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 21, versiculo: 1 },
      { libro: "1 Juan", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 43, versiculo: 4 }
    ],
    fraseEmpatica: [
      "Este es el día que hizo el Señor; nos gozaremos en él.",
      "Regocijaos en el Señor siempre.",
      "En tu presencia hay plenitud de gozo.",
      "El gozo del Señor es vuestra fortaleza.",
      "La alegría es el idioma del cielo."
    ]
  },
  {
    nombre: "Paciencia / Perseverancia",
    keywords: ["paciencia","perseverancia","constancia","esperar","resistencia","aguante"],
    referencias: [
      { libro: "Romanos", capitulo: 12, versiculo: 12 },
      { libro: "Santiago", capitulo: 1, versiculo: 4 },
      { libro: "Salmos", capitulo: 37, versiculo: 7 },
      { libro: "Hebreos", capitulo: 10, versiculo: 36 },
      { libro: "Proverbios", capitulo: 14, versiculo: 29 },
      { libro: "Salmos", capitulo: 40, versiculo: 1 },
      { libro: "2 Pedro", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 27, versiculo: 14 },
      { libro: "Gálatas", capitulo: 6, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 9 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 26 },
      { libro: "Salmos", capitulo: 130, versiculo: 5 },
      { libro: "Romanos", capitulo: 8, versiculo: 25 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Colosenses", capitulo: 1, versiculo: 11 },
      { libro: "Salmos", capitulo: 25, versiculo: 3 },
      { libro: "Isaías", capitulo: 30, versiculo: 18 },
      { libro: "Salmos", capitulo: 33, versiculo: 20 },
      { libro: "Santiago", capitulo: 5, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 84 },
      { libro: "Mateo", capitulo: 24, versiculo: 13 },
      { libro: "Salmos", capitulo: 71, versiculo: 14 },
      { libro: "Apocalipsis", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 37, versiculo: 34 },
      { libro: "1 Tesalonicenses", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 92, versiculo: 12 },
      { libro: "Hebreos", capitulo: 6, versiculo: 12 },
      { libro: "Salmos", capitulo: 52, versiculo: 9 },
      { libro: "Lucas", capitulo: 8, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 5 },
      { libro: "Romanos", capitulo: 5, versiculo: 3 },
      { libro: "Salmos", capitulo: 69, versiculo: 13 },
      { libro: "Filipenses", capitulo: 3, versiculo: 14 }
    ],
    fraseEmpatica: [
      "Gozosos en la esperanza, pacientes en la tribulación.",
      "La paciencia produce carácter probado.",
      "Guarda silencio ante el Señor y espera en Él.",
      "No os canséis de hacer el bien.",
      "Dios nunca llega tarde; sus tiempos son perfectos."
    ]
  },
  {
    nombre: "Humildad",
    keywords: ["humildad","sencillez","mansedumbre","pequeñez","no orgullo"],
    referencias: [
      { libro: "Mateo", capitulo: 23, versiculo: 12 },
      { libro: "Santiago", capitulo: 4, versiculo: 10 },
      { libro: "Proverbios", capitulo: 22, versiculo: 4 },
      { libro: "Miqueas", capitulo: 6, versiculo: 8 },
      { libro: "Salmos", capitulo: 25, versiculo: 9 },
      { libro: "1 Pedro", capitulo: 5, versiculo: 6 },
      { libro: "Salmos", capitulo: 149, versiculo: 4 },
      { libro: "Filipenses", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 131, versiculo: 1 },
      { libro: "Efesios", capitulo: 4, versiculo: 2 },
      { libro: "Salmos", capitulo: 138, versiculo: 6 },
      { libro: "Colosenses", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 51, versiculo: 17 },
      { libro: "Mateo", capitulo: 11, versiculo: 29 },
      { libro: "Salmos", capitulo: 34, versiculo: 2 },
      { libro: "Romanos", capitulo: 12, versiculo: 3 },
      { libro: "Salmos", capitulo: 147, versiculo: 6 },
      { libro: "Lucas", capitulo: 14, versiculo: 11 },
      { libro: "Salmos", capitulo: 113, versiculo: 6 },
      { libro: "Proverbios", capitulo: 29, versiculo: 23 },
      { libro: "Salmos", capitulo: 18, versiculo: 27 },
      { libro: "Isaías", capitulo: 66, versiculo: 2 },
      { libro: "Salmos", capitulo: 119, versiculo: 21 },
      { libro: "2 Crónicas", capitulo: 7, versiculo: 14 },
      { libro: "Salmos", capitulo: 10, versiculo: 17 },
      { libro: "Sofonías", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 37, versiculo: 11 },
      { libro: "Mateo", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 76, versiculo: 9 },
      { libro: "Daniel", capitulo: 10, versiculo: 12 },
      { libro: "Salmos", capitulo: 86, versiculo: 1 },
      { libro: "Lucas", capitulo: 1, versiculo: 52 },
      { libro: "Salmos", capitulo: 145, versiculo: 14 }
    ],
    fraseEmpatica: [
      "El que se enaltece será humillado.",
      "Humillaos delante del Señor y Él os exaltará.",
      "Aprended de mí, que soy manso y humilde de corazón.",
      "La grandeza ante Dios se mide por la pequeñez ante los hombres.",
      "Dios resiste a los soberbios, pero da gracia a los humildes."
    ]
  },
  {
    nombre: "Sabiduría / Discernimiento",
    keywords: ["sabiduría","discernimiento","entendimiento","inteligencia","prudencia","consejo"],
    referencias: [
      { libro: "Santiago", capitulo: 1, versiculo: 5 },
      { libro: "Proverbios", capitulo: 2, versiculo: 6 },
      { libro: "Salmos", capitulo: 111, versiculo: 10 },
      { libro: "Proverbios", capitulo: 4, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 105 },
      { libro: "1 Reyes", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 19, versiculo: 7 },
      { libro: "Proverbios", capitulo: 3, versiculo: 13 },
      { libro: "Salmos", capitulo: 90, versiculo: 12 },
      { libro: "Efesios", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 66 },
      { libro: "Colosenses", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "Isaías", capitulo: 11, versiculo: 2 },
      { libro: "Salmos", capitulo: 25, versiculo: 12 },
      { libro: "Proverbios", capitulo: 16, versiculo: 16 },
      { libro: "Salmos", capitulo: 37, versiculo: 30 },
      { libro: "Daniel", capitulo: 2, versiculo: 21 },
      { libro: "Salmos", capitulo: 119, versiculo: 98 },
      { libro: "1 Corintios", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 51, versiculo: 6 },
      { libro: "Proverbios", capitulo: 11, versiculo: 2 },
      { libro: "Salmos", capitulo: 107, versiculo: 43 },
      { libro: "Romanos", capitulo: 11, versiculo: 33 },
      { libro: "Salmos", capitulo: 139, versiculo: 6 },
      { libro: "Proverbios", capitulo: 24, versiculo: 3 },
      { libro: "Salmos", capitulo: 104, versiculo: 24 },
      { libro: "Eclesiastés", capitulo: 2, versiculo: 26 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Job", capitulo: 12, versiculo: 13 },
      { libro: "Salmos", capitulo: 136, versiculo: 5 },
      { libro: "Isaías", capitulo: 40, versiculo: 28 },
      { libro: "Salmos", capitulo: 147, versiculo: 5 }
    ],
    fraseEmpatica: [
      "Si alguno tiene falta de sabiduría, pídala a Dios.",
      "El principio de la sabiduría es el temor del Señor.",
      "Sabiduría ante todo; adquiere sabiduría.",
      "Lámpara es a mis pies tu palabra.",
      "La verdadera sabiduría no está en saber mucho, sino en amar mucho."
    ]
  },
  {
    nombre: "Trabajo / Desempleo",
    keywords: ["trabajo","empleo","desempleo","paro","profesión","oficio","negocio"],
    referencias: [
      { libro: "Colosenses", capitulo: 3, versiculo: 23 },
      { libro: "Proverbios", capitulo: 16, versiculo: 3 },
      { libro: "Salmos", capitulo: 90, versiculo: 17 },
      { libro: "2 Tesalonicenses", capitulo: 3, versiculo: 10 },
      { libro: "Proverbios", capitulo: 12, versiculo: 11 },
      { libro: "Salmos", capitulo: 128, versiculo: 2 },
      { libro: "Eclesiastés", capitulo: 9, versiculo: 10 },
      { libro: "Proverbios", capitulo: 14, versiculo: 23 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "1 Timoteo", capitulo: 5, versiculo: 18 },
      { libro: "Salmos", capitulo: 104, versiculo: 23 },
      { libro: "Proverbios", capitulo: 22, versiculo: 29 },
      { libro: "Salmos", capitulo: 34, versiculo: 10 },
      { libro: "Mateo", capitulo: 25, versiculo: 21 },
      { libro: "Salmos", capitulo: 127, versiculo: 1 },
      { libro: "Génesis", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 112, versiculo: 3 },
      { libro: "Proverbios", capitulo: 10, versiculo: 4 },
      { libro: "Salmos", capitulo: 145, versiculo: 15 },
      { libro: "Efesios", capitulo: 4, versiculo: 28 },
      { libro: "Salmos", capitulo: 68, versiculo: 6 },
      { libro: "Deuteronomio", capitulo: 8, versiculo: 18 },
      { libro: "Salmos", capitulo: 1, versiculo: 3 },
      { libro: "Lucas", capitulo: 10, versiculo: 7 },
      { libro: "Salmos", capitulo: 25, versiculo: 12 },
      { libro: "Proverbios", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 4 },
      { libro: "1 Corintios", capitulo: 15, versiculo: 58 },
      { libro: "Salmos", capitulo: 115, versiculo: 12 },
      { libro: "Proverbios", capitulo: 28, versiculo: 19 },
      { libro: "Salmos", capitulo: 132, versiculo: 15 },
      { libro: "Isaías", capitulo: 65, versiculo: 21 },
      { libro: "Salmos", capitulo: 128, versiculo: 1 }
    ],
    fraseEmpatica: [
      "Todo lo que hagáis, hacedlo de corazón.",
      "Encomienda al Señor tus obras.",
      "El trabajo es un don, no un castigo.",
      "Dios es el mejor jefe que puedas tener.",
      "Bienaventurado el que come del trabajo de sus manos."
    ]
  },
  {
    nombre: "Estudios / Exámenes",
    keywords: ["estudios","examen","estudiar","aprender","prueba","conocimiento"],
    referencias: [
      { libro: "Proverbios", capitulo: 1, versiculo: 7 },
      { libro: "Santiago", capitulo: 1, versiculo: 5 },
      { libro: "Salmos", capitulo: 119, versiculo: 99 },
      { libro: "Proverbios", capitulo: 9, versiculo: 10 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "2 Timoteo", capitulo: 2, versiculo: 15 },
      { libro: "Salmos", capitulo: 119, versiculo: 66 },
      { libro: "Proverbios", capitulo: 2, versiculo: 3 },
      { libro: "Salmos", capitulo: 25, versiculo: 4 },
      { libro: "Daniel", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 34 },
      { libro: "Colosenses", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 30 },
      { libro: "1 Reyes", capitulo: 3, versiculo: 12 },
      { libro: "Salmos", capitulo: 119, versiculo: 73 },
      { libro: "Proverbios", capitulo: 4, versiculo: 5 },
      { libro: "Salmos", capitulo: 94, versiculo: 10 },
      { libro: "Efesios", capitulo: 1, versiculo: 18 },
      { libro: "Salmos", capitulo: 16, versiculo: 7 },
      { libro: "Lucas", capitulo: 2, versiculo: 52 },
      { libro: "Salmos", capitulo: 71, versiculo: 17 },
      { libro: "Isaías", capitulo: 50, versiculo: 4 },
      { libro: "Salmos", capitulo: 119, versiculo: 9 },
      { libro: "Proverbios", capitulo: 16, versiculo: 16 },
      { libro: "Salmos", capitulo: 49, versiculo: 3 },
      { libro: "Mateo", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 119, versiculo: 27 },
      { libro: "1 Corintios", capitulo: 8, versiculo: 1 },
      { libro: "Salmos", capitulo: 78, versiculo: 72 },
      { libro: "Proverbios", capitulo: 18, versiculo: 15 },
      { libro: "Salmos", capitulo: 138, versiculo: 3 },
      { libro: "Jeremías", capitulo: 33, versiculo: 3 },
      { libro: "Salmos", capitulo: 143, versiculo: 10 }
    ],
    fraseEmpatica: [
      "El principio de la sabiduría es el temor del Señor.",
      "Si alguno tiene falta de sabiduría, pídala a Dios.",
      "Procura con diligencia presentarte aprobado.",
      "Dios te ha dado inteligencia; úsala para su gloria.",
      "Ante un examen, respira: no estás solo."
    ]
  },
  {
    nombre: "Ayuda económica / Providencia",
    keywords: ["dinero","deuda","económico","pobreza","necesidad","provisión"],
    referencias: [
      { libro: "Filipenses", capitulo: 4, versiculo: 19 },
      { libro: "Salmos", capitulo: 23, versiculo: 1 },
      { libro: "Mateo", capitulo: 6, versiculo: 26 },
      { libro: "Salmos", capitulo: 34, versiculo: 10 },
      { libro: "Proverbios", capitulo: 3, versiculo: 9 },
      { libro: "Salmos", capitulo: 37, versiculo: 25 },
      { libro: "Malaquías", capitulo: 3, versiculo: 10 },
      { libro: "Salmos", capitulo: 112, versiculo: 3 },
      { libro: "2 Corintios", capitulo: 9, versiculo: 8 },
      { libro: "Salmos", capitulo: 132, versiculo: 15 },
      { libro: "Lucas", capitulo: 12, versiculo: 24 },
      { libro: "Salmos", capitulo: 145, versiculo: 16 },
      { libro: "Deuteronomio", capitulo: 28, versiculo: 12 },
      { libro: "Salmos", capitulo: 104, versiculo: 28 },
      { libro: "1 Timoteo", capitulo: 6, versiculo: 17 },
      { libro: "Salmos", capitulo: 107, versiculo: 9 },
      { libro: "Proverbios", capitulo: 11, versiculo: 24 },
      { libro: "Salmos", capitulo: 37, versiculo: 19 },
      { libro: "Éxodo", capitulo: 16, versiculo: 4 },
      { libro: "Salmos", capitulo: 84, versiculo: 11 },
      { libro: "Mateo", capitulo: 7, versiculo: 11 },
      { libro: "Salmos", capitulo: 81, versiculo: 10 },
      { libro: "Santiago", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 127, versiculo: 2 },
      { libro: "Proverbios", capitulo: 22, versiculo: 7 },
      { libro: "Salmos", capitulo: 55, versiculo: 22 },
      { libro: "1 Juan", capitulo: 3, versiculo: 17 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Génesis", capitulo: 22, versiculo: 14 },
      { libro: "Salmos", capitulo: 50, versiculo: 10 },
      { libro: "Lucas", capitulo: 6, versiculo: 38 },
      { libro: "Salmos", capitulo: 112, versiculo: 5 },
      { libro: "Proverbios", capitulo: 28, versiculo: 27 }
    ],
    fraseEmpatica: [
      "Mi Dios proveerá a todas vuestras necesidades.",
      "El Señor es mi pastor, nada me falta.",
      "Los que buscan al Señor no carecen de ningún bien.",
      "Dios es tu proveedor, no solo de dinero.",
      "Confía: el que alimenta a los pájaros no te dejará."
    ]
  },
  {
    nombre: "Justicia / Injusticia",
    keywords: ["justicia","injusticia","injusto","desigualdad","rectitud","juicio"],
    referencias: [
      { libro: "Miqueas", capitulo: 6, versiculo: 8 },
      { libro: "Isaías", capitulo: 1, versiculo: 17 },
      { libro: "Salmos", capitulo: 82, versiculo: 3 },
      { libro: "Proverbios", capitulo: 21, versiculo: 15 },
      { libro: "Salmos", capitulo: 37, versiculo: 28 },
      { libro: "Amós", capitulo: 5, versiculo: 24 },
      { libro: "Salmos", capitulo: 33, versiculo: 5 },
      { libro: "Lucas", capitulo: 18, versiculo: 7 },
      { libro: "Salmos", capitulo: 103, versiculo: 6 },
      { libro: "Deuteronomio", capitulo: 16, versiculo: 20 },
      { libro: "Salmos", capitulo: 140, versiculo: 12 },
      { libro: "Romanos", capitulo: 12, versiculo: 19 },
      { libro: "Salmos", capitulo: 9, versiculo: 9 },
      { libro: "Isaías", capitulo: 61, versiculo: 8 },
      { libro: "Salmos", capitulo: 72, versiculo: 4 },
      { libro: "Jeremías", capitulo: 22, versiculo: 3 },
      { libro: "Salmos", capitulo: 146, versiculo: 7 },
      { libro: "Mateo", capitulo: 5, versiculo: 6 },
      { libro: "Salmos", capitulo: 11, versiculo: 7 },
      { libro: "Santiago", capitulo: 5, versiculo: 4 },
      { libro: "Salmos", capitulo: 94, versiculo: 15 },
      { libro: "Proverbios", capitulo: 29, versiculo: 26 },
      { libro: "Salmos", capitulo: 58, versiculo: 11 },
      { libro: "Lucas", capitulo: 11, versiculo: 42 },
      { libro: "Salmos", capitulo: 99, versiculo: 4 },
      { libro: "Job", capitulo: 34, versiculo: 12 },
      { libro: "Salmos", capitulo: 45, versiculo: 6 },
      { libro: "Apocalipsis", capitulo: 19, versiculo: 11 },
      { libro: "Salmos", capitulo: 119, versiculo: 137 },
      { libro: "Oseas", capitulo: 12, versiculo: 6 },
      { libro: "Salmos", capitulo: 75, versiculo: 2 },
      { libro: "2 Tesalonicenses", capitulo: 1, versiculo: 6 },
      { libro: "Salmos", capitulo: 98, versiculo: 9 }
    ],
    fraseEmpatica: [
      "Hacer justicia, amar misericordia y humillarte ante tu Dios.",
      "Bienaventurados los que tienen hambre y sed de justicia.",
      "El Señor ama la justicia.",
      "Mía es la venganza, yo pagaré, dice el Señor.",
      "Aunque el mundo sea injusto, el Juez Supremo ve cada lágrima."
    ]
  },
  {
    nombre: "Esperanza en el futuro",
    keywords: ["esperanza","futuro","mañana","ilusión","visión","plan"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Romanos", capitulo: 15, versiculo: 13 },
      { libro: "Salmos", capitulo: 33, versiculo: 22 },
      { libro: "Isaías", capitulo: 40, versiculo: 31 },
      { libro: "Salmos", capitulo: 62, versiculo: 5 },
      { libro: "Lamentaciones", capitulo: 3, versiculo: 24 },
      { libro: "Salmos", capitulo: 71, versiculo: 5 },
      { libro: "Proverbios", capitulo: 23, versiculo: 18 },
      { libro: "Salmos", capitulo: 130, versiculo: 7 },
      { libro: "Romanos", capitulo: 8, versiculo: 24 },
      { libro: "Salmos", capitulo: 39, versiculo: 7 },
      { libro: "Isaías", capitulo: 43, versiculo: 19 },
      { libro: "Salmos", capitulo: 16, versiculo: 9 },
      { libro: "Hebreos", capitulo: 11, versiculo: 1 },
      { libro: "Salmos", capitulo: 146, versiculo: 5 },
      { libro: "Jeremías", capitulo: 31, versiculo: 17 },
      { libro: "Salmos", capitulo: 119, versiculo: 49 },
      { libro: "Tito", capitulo: 2, versiculo: 13 },
      { libro: "Salmos", capitulo: 37, versiculo: 37 },
      { libro: "Miqueas", capitulo: 7, versiculo: 7 },
      { libro: "Salmos", capitulo: 42, versiculo: 11 },
      { libro: "Colosenses", capitulo: 1, versiculo: 27 },
      { libro: "Salmos", capitulo: 27, versiculo: 13 },
      { libro: "1 Pedro", capitulo: 1, versiculo: 3 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Apocalipsis", capitulo: 21, versiculo: 5 },
      { libro: "Salmos", capitulo: 31, versiculo: 24 },
      { libro: "Zacarías", capitulo: 9, versiculo: 12 },
      { libro: "Salmos", capitulo: 84, versiculo: 11 },
      { libro: "2 Corintios", capitulo: 4, versiculo: 17 },
      { libro: "Salmos", capitulo: 62, versiculo: 8 },
      { libro: "Romanos", capitulo: 5, versiculo: 5 },
      { libro: "Salmos", capitulo: 121, versiculo: 8 }
    ],
    fraseEmpatica: [
      "Porque yo sé los planes que tengo para ti.",
      "El Dios de la esperanza os llene de gozo y paz.",
      "Los que esperan en el Señor renovarán sus fuerzas.",
      "He aquí que yo hago algo nuevo.",
      "Lo mejor está por venir."
    ]
  },
  {
    nombre: "Vocación / Propósito de vida",
    keywords: ["vocación","propósito","llamado","misión","sentido","para qué estoy aquí"],
    referencias: [
      { libro: "Jeremías", capitulo: 29, versiculo: 11 },
      { libro: "Efesios", capitulo: 2, versiculo: 10 },
      { libro: "Salmos", capitulo: 138, versiculo: 8 },
      { libro: "Romanos", capitulo: 8, versiculo: 28 },
      { libro: "Salmos", capitulo: 57, versiculo: 2 },
      { libro: "Proverbios", capitulo: 19, versiculo: 21 },
      { libro: "Salmos", capitulo: 32, versiculo: 8 },
      { libro: "1 Corintios", capitulo: 7, versiculo: 17 },
      { libro: "Salmos", capitulo: 37, versiculo: 4 },
      { libro: "Isaías", capitulo: 6, versiculo: 8 },
      { libro: "Salmos", capitulo: 16, versiculo: 11 },
      { libro: "Mateo", capitulo: 22, versiculo: 14 },
      { libro: "Salmos", capitulo: 25, versiculo: 14 },
      { libro: "1 Pedro", capitulo: 2, versiculo: 9 },
      { libro: "Salmos", capitulo: 139, versiculo: 16 },
      { libro: "Juan", capitulo: 15, versiculo: 16 },
      { libro: "Salmos", capitulo: 119, versiculo: 35 },
      { libro: "Filipenses", capitulo: 3, versiculo: 14 },
      { libro: "Salmos", capitulo: 143, versiculo: 8 },
      { libro: "Gálatas", capitulo: 1, versiculo: 15 },
      { libro: "Salmos", capitulo: 40, versiculo: 8 },
      { libro: "2 Timoteo", capitulo: 1, versiculo: 9 },
      { libro: "Salmos", capitulo: 27, versiculo: 11 },
      { libro: "Colosenses", capitulo: 1, versiculo: 16 },
      { libro: "Salmos", capitulo: 73, versiculo: 24 },
      { libro: "Hechos", capitulo: 13, versiculo: 2 },
      { libro: "Salmos", capitulo: 100, versiculo: 3 },
      { libro: "Apocalipsis", capitulo: 17, versiculo: 14 },
      { libro: "Salmos", capitulo: 84, versiculo: 5 },
      { libro: "Lucas", capitulo: 1, versiculo: 79 },
      { libro: "Salmos", capitulo: 119, versiculo: 125 },
      { libro: "Romanos", capitulo: 12, versiculo: 6 },
      { libro: "Salmos", capitulo: 108, versiculo: 13 }
    ],
    fraseEmpatica: [
      "Antes de formarte en el vientre te conocí.",
      "Somos hechura suya, creados para buenas obras.",
      "El Señor cumplirá su propósito en mí.",
      "No estás aquí por casualidad.",
      "Escucha el susurro divino que te llama por tu nombre."
    ]
  }
];

// ===== FUNCIONES DE BÚSQUEDA =====
function detectarCategoria(texto) {
  const textoLower = texto.toLowerCase();
  let mejorCategoria = null;
  let maxCoincidencias = 0;
  for (const categoria of categories) {
    let coincidencias = 0;
    for (const keyword of categoria.keywords) {
      if (textoLower.includes(keyword.toLowerCase())) coincidencias++;
    }
    if (coincidencias > maxCoincidencias) {
      maxCoincidencias = coincidencias;
      mejorCategoria = categoria;
    }
  }
  if (!mejorCategoria) mejorCategoria = categories[Math.floor(Math.random() * categories.length)];
  return mejorCategoria;
}

function obtenerTextoVersiculo(referencia) {
  try {
    for (const testamento in bibleData) {
      for (const libro in bibleData[testamento]) {
        if (libro.toLowerCase().includes(referencia.libro.toLowerCase())) {
          const capitulo = bibleData[testamento][libro][referencia.capitulo.toString()];
          if (capitulo && capitulo[referencia.versiculo.toString()]) {
            return capitulo[referencia.versiculo.toString()];
          }
        }
      }
    }
  } catch (e) { console.error(e); }
  return "El Señor es mi pastor, nada me falta.";
}
